import type { Audit, AuditTarget } from '@prisma/client';

import type {
  AuditAction,
  AuditMetadata,
  AuditTargetType,
} from '@eridu/api-types/audits';

/**
 * Domain-level payload for creating an `Audit` envelope plus one or more
 * `AuditTarget` rows in a single nested write.
 *
 * `actorId` is `null` for engine writes (extraction pipeline) and populated for
 * manager-initiated overrides. `uid` is generated by `AuditService` before the
 * payload reaches the repository.
 */
export type CreateAuditPayload = {
  uid: string;
  action: AuditAction;
  actorId?: bigint | null;
  ipAddress?: string | null;
  userAgent?: string | null;
  /**
   * Free-text justification supplied by the actor on OVERRIDE-class writes.
   * Nullable because engine writes never carry a reason. Required-ness is
   * enforced per writer (e.g. `studio-shift.service` rejects an hourly_rate
   * edit without `override_reason`), not by `AuditService`.
   */
  reason?: string | null;
  metadata?: AuditMetadata;
  /**
   * Set only on `schedule_publish_impact` rows written during a schedule
   * publish call, linking the row to its `PublishRun` batch. Null/omitted for
   * every other audit writer.
   */
  publishRunId?: bigint | null;
  targets: CreateAuditTargetPayload[];
};

/**
 * Polymorphic target reference. The repository routes `targetId` into the
 * correct typed FK column (`showId`, `showCreatorId`, `showPlatformId`, or
 * `studioShiftId`) based on `targetType`, so deletes on the target row cascade
 * cleanly into the junction without orphaning the parent `Audit`.
 */
export type CreateAuditTargetPayload = {
  targetType: AuditTargetType;
  targetId: bigint;
};

export type AuditTargetWithRelations = AuditTarget & {
  show?: { uid: string } | null;
  showCreator?: { uid: string } | null;
  showPlatform?: { uid: string } | null;
  studioShift?: { uid: string } | null;
};

/** `Audit` row with its `AuditTarget` rows eagerly included. */
export type AuditWithTargets = Audit & {
  targets: AuditTargetWithRelations[];
  actor?: { uid: string } | null;
};

/** Filter tuple consumed by `AuditRepository.findForTargets`. */
export type AuditTargetFilter = {
  targetType: AuditTargetType;
  targetId: bigint;
};
