/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as SystemRouteRouteImport } from './routes/system/route'
import { Route as StudiosRouteRouteImport } from './routes/studios/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudiosStudioIdRouteRouteImport } from './routes/studios/$studioId/route'
import { Route as SystemUsersIndexRouteImport } from './routes/system/users/index'
import { Route as SystemTasksIndexRouteImport } from './routes/system/tasks/index'
import { Route as SystemTaskTemplatesIndexRouteImport } from './routes/system/task-templates/index'
import { Route as SystemStudiosIndexRouteImport } from './routes/system/studios/index'
import { Route as SystemShowsIndexRouteImport } from './routes/system/shows/index'
import { Route as SystemShowTypesIndexRouteImport } from './routes/system/show-types/index'
import { Route as SystemShowStatusesIndexRouteImport } from './routes/system/show-statuses/index'
import { Route as SystemShowStandardsIndexRouteImport } from './routes/system/show-standards/index'
import { Route as SystemSchedulesIndexRouteImport } from './routes/system/schedules/index'
import { Route as SystemPlatformsIndexRouteImport } from './routes/system/platforms/index'
import { Route as SystemMembershipsIndexRouteImport } from './routes/system/memberships/index'
import { Route as SystemCreatorsIndexRouteImport } from './routes/system/creators/index'
import { Route as SystemCompensationLineItemsIndexRouteImport } from './routes/system/compensation-line-items/index'
import { Route as SystemClientsIndexRouteImport } from './routes/system/clients/index'
import { Route as StudiosStudioIdTaskTemplatesRouteImport } from './routes/studios/$studioId/task-templates'
import { Route as StudiosStudioIdTaskSetupRouteImport } from './routes/studios/$studioId/task-setup'
import { Route as StudiosStudioIdTaskReviewRouteImport } from './routes/studios/$studioId/task-review'
import { Route as StudiosStudioIdTaskReportsRouteImport } from './routes/studios/$studioId/task-reports'
import { Route as StudiosStudioIdShowsRouteImport } from './routes/studios/$studioId/shows'
import { Route as StudiosStudioIdShowRunReviewRouteImport } from './routes/studios/$studioId/show-run-review'
import { Route as StudiosStudioIdShiftsRouteImport } from './routes/studios/$studioId/shifts'
import { Route as StudiosStudioIdSharedFieldsRouteImport } from './routes/studios/$studioId/shared-fields'
import { Route as StudiosStudioIdPerformanceRouteImport } from './routes/studios/$studioId/performance'
import { Route as StudiosStudioIdMyTasksRouteImport } from './routes/studios/$studioId/my-tasks'
import { Route as StudiosStudioIdMyShiftsRouteImport } from './routes/studios/$studioId/my-shifts'
import { Route as StudiosStudioIdMyCompensationsRouteImport } from './routes/studios/$studioId/my-compensations'
import { Route as StudiosStudioIdMembersRouteImport } from './routes/studios/$studioId/members'
import { Route as StudiosStudioIdDashboardRouteImport } from './routes/studios/$studioId/dashboard'
import { Route as StudiosStudioIdCreatorsRouteImport } from './routes/studios/$studioId/creators'
import { Route as StudiosStudioIdCreatorMappingRouteImport } from './routes/studios/$studioId/creator-mapping'
import { Route as StudiosStudioIdCostsRouteImport } from './routes/studios/$studioId/costs'
import { Route as StudiosStudioIdTaskTemplatesIndexRouteImport } from './routes/studios/$studioId/task-templates/index'
import { Route as StudiosStudioIdTaskSetupIndexRouteImport } from './routes/studios/$studioId/task-setup/index'
import { Route as StudiosStudioIdTaskReviewIndexRouteImport } from './routes/studios/$studioId/task-review/index'
import { Route as StudiosStudioIdTaskReportsIndexRouteImport } from './routes/studios/$studioId/task-reports/index'
import { Route as StudiosStudioIdShowsIndexRouteImport } from './routes/studios/$studioId/shows/index'
import { Route as StudiosStudioIdShiftsIndexRouteImport } from './routes/studios/$studioId/shifts/index'
import { Route as StudiosStudioIdMembersIndexRouteImport } from './routes/studios/$studioId/members/index'
import { Route as StudiosStudioIdCreatorsIndexRouteImport } from './routes/studios/$studioId/creators/index'
import { Route as StudiosStudioIdCreatorMappingIndexRouteImport } from './routes/studios/$studioId/creator-mapping/index'
import { Route as SystemShowsShowIdTasksRouteImport } from './routes/system/shows/$showId/tasks'
import { Route as StudiosStudioIdTaskTemplatesNewRouteImport } from './routes/studios/$studioId/task-templates/new'
import { Route as StudiosStudioIdTaskTemplatesTemplateIdRouteImport } from './routes/studios/$studioId/task-templates/$templateId'
import { Route as StudiosStudioIdTaskReportsResultsRouteImport } from './routes/studios/$studioId/task-reports/results'
import { Route as StudiosStudioIdTaskReportsBuilderRouteImport } from './routes/studios/$studioId/task-reports/builder'
import { Route as StudiosStudioIdShowsShowIdRouteRouteImport } from './routes/studios/$studioId/shows/$showId/route'
import { Route as StudiosStudioIdShiftsShiftIdRouteRouteImport } from './routes/studios/$studioId/shifts/$shiftId/route'
import { Route as StudiosStudioIdMembersMemberIdRouteRouteImport } from './routes/studios/$studioId/members/$memberId/route'
import { Route as StudiosStudioIdCreatorsCreatorIdRouteRouteImport } from './routes/studios/$studioId/creators/$creatorId/route'
import { Route as SystemStudiosStudioIdStudioRoomsIndexRouteImport } from './routes/system/studios/$studioId/studio-rooms/index'
import { Route as SystemSchedulesScheduleIdSnapshotsIndexRouteImport } from './routes/system/schedules/$scheduleId/snapshots/index'
import { Route as StudiosStudioIdShowsShowIdIndexRouteImport } from './routes/studios/$studioId/shows/$showId/index'
import { Route as StudiosStudioIdShiftsShiftIdIndexRouteImport } from './routes/studios/$studioId/shifts/$shiftId/index'
import { Route as StudiosStudioIdMembersMemberIdIndexRouteImport } from './routes/studios/$studioId/members/$memberId/index'
import { Route as StudiosStudioIdCreatorsCreatorIdIndexRouteImport } from './routes/studios/$studioId/creators/$creatorId/index'
import { Route as StudiosStudioIdShowsShowIdTasksRouteImport } from './routes/studios/$studioId/shows/$showId/tasks'
import { Route as StudiosStudioIdShowsShowIdPerformanceRouteImport } from './routes/studios/$studioId/shows/$showId/performance'
import { Route as StudiosStudioIdShowsShowIdCompensationRouteImport } from './routes/studios/$studioId/shows/$showId/compensation'
import { Route as StudiosStudioIdShowsShowIdActualsRouteImport } from './routes/studios/$studioId/shows/$showId/actuals'
import { Route as StudiosStudioIdShiftsShiftIdCompensationRouteImport } from './routes/studios/$studioId/shifts/$shiftId/compensation'
import { Route as StudiosStudioIdMembersMemberIdCompensationsRouteImport } from './routes/studios/$studioId/members/$memberId/compensations'
import { Route as StudiosStudioIdCreatorsCreatorIdCompensationsRouteImport } from './routes/studios/$studioId/creators/$creatorId/compensations'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemRouteRoute = SystemRouteRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const StudiosRouteRoute = StudiosRouteRouteImport.update({
  id: '/studios',
  path: '/studios',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudiosStudioIdRouteRoute = StudiosStudioIdRouteRouteImport.update({
  id: '/$studioId',
  path: '/$studioId',
  getParentRoute: () => StudiosRouteRoute,
} as any)
const SystemUsersIndexRoute = SystemUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => SystemRouteRoute,
} as any)
const SystemTasksIndexRoute = SystemTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => SystemRouteRoute,
} as any)
const SystemTaskTemplatesIndexRoute =
  SystemTaskTemplatesIndexRouteImport.update({
    id: '/task-templates/',
    path: '/task-templates/',
    getParentRoute: () => SystemRouteRoute,
  } as any)
const SystemStudiosIndexRoute = SystemStudiosIndexRouteImport.update({
  id: '/studios/',
  path: '/studios/',
  getParentRoute: () => SystemRouteRoute,
} as any)
const SystemShowsIndexRoute = SystemShowsIndexRouteImport.update({
  id: '/shows/',
  path: '/shows/',
  getParentRoute: () => SystemRouteRoute,
} as any)
const SystemShowTypesIndexRoute = SystemShowTypesIndexRouteImport.update({
  id: '/show-types/',
  path: '/show-types/',
  getParentRoute: () => SystemRouteRoute,
} as any)
const SystemShowStatusesIndexRoute = SystemShowStatusesIndexRouteImport.update({
  id: '/show-statuses/',
  path: '/show-statuses/',
  getParentRoute: () => SystemRouteRoute,
} as any)
const SystemShowStandardsIndexRoute =
  SystemShowStandardsIndexRouteImport.update({
    id: '/show-standards/',
    path: '/show-standards/',
    getParentRoute: () => SystemRouteRoute,
  } as any)
const SystemSchedulesIndexRoute = SystemSchedulesIndexRouteImport.update({
  id: '/schedules/',
  path: '/schedules/',
  getParentRoute: () => SystemRouteRoute,
} as any)
const SystemPlatformsIndexRoute = SystemPlatformsIndexRouteImport.update({
  id: '/platforms/',
  path: '/platforms/',
  getParentRoute: () => SystemRouteRoute,
} as any)
const SystemMembershipsIndexRoute = SystemMembershipsIndexRouteImport.update({
  id: '/memberships/',
  path: '/memberships/',
  getParentRoute: () => SystemRouteRoute,
} as any)
const SystemCreatorsIndexRoute = SystemCreatorsIndexRouteImport.update({
  id: '/creators/',
  path: '/creators/',
  getParentRoute: () => SystemRouteRoute,
} as any)
const SystemCompensationLineItemsIndexRoute =
  SystemCompensationLineItemsIndexRouteImport.update({
    id: '/compensation-line-items/',
    path: '/compensation-line-items/',
    getParentRoute: () => SystemRouteRoute,
  } as any)
const SystemClientsIndexRoute = SystemClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => SystemRouteRoute,
} as any)
const StudiosStudioIdTaskTemplatesRoute =
  StudiosStudioIdTaskTemplatesRouteImport.update({
    id: '/task-templates',
    path: '/task-templates',
    getParentRoute: () => StudiosStudioIdRouteRoute,
  } as any)
const StudiosStudioIdTaskSetupRoute =
  StudiosStudioIdTaskSetupRouteImport.update({
    id: '/task-setup',
    path: '/task-setup',
    getParentRoute: () => StudiosStudioIdRouteRoute,
  } as any)
const StudiosStudioIdTaskReviewRoute =
  StudiosStudioIdTaskReviewRouteImport.update({
    id: '/task-review',
    path: '/task-review',
    getParentRoute: () => StudiosStudioIdRouteRoute,
  } as any)
const StudiosStudioIdTaskReportsRoute =
  StudiosStudioIdTaskReportsRouteImport.update({
    id: '/task-reports',
    path: '/task-reports',
    getParentRoute: () => StudiosStudioIdRouteRoute,
  } as any)
const StudiosStudioIdShowsRoute = StudiosStudioIdShowsRouteImport.update({
  id: '/shows',
  path: '/shows',
  getParentRoute: () => StudiosStudioIdRouteRoute,
} as any)
const StudiosStudioIdShowRunReviewRoute =
  StudiosStudioIdShowRunReviewRouteImport.update({
    id: '/show-run-review',
    path: '/show-run-review',
    getParentRoute: () => StudiosStudioIdRouteRoute,
  } as any)
const StudiosStudioIdShiftsRoute = StudiosStudioIdShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => StudiosStudioIdRouteRoute,
} as any)
const StudiosStudioIdSharedFieldsRoute =
  StudiosStudioIdSharedFieldsRouteImport.update({
    id: '/shared-fields',
    path: '/shared-fields',
    getParentRoute: () => StudiosStudioIdRouteRoute,
  } as any)
const StudiosStudioIdPerformanceRoute =
  StudiosStudioIdPerformanceRouteImport.update({
    id: '/performance',
    path: '/performance',
    getParentRoute: () => StudiosStudioIdRouteRoute,
  } as any)
const StudiosStudioIdMyTasksRoute = StudiosStudioIdMyTasksRouteImport.update({
  id: '/my-tasks',
  path: '/my-tasks',
  getParentRoute: () => StudiosStudioIdRouteRoute,
} as any)
const StudiosStudioIdMyShiftsRoute = StudiosStudioIdMyShiftsRouteImport.update({
  id: '/my-shifts',
  path: '/my-shifts',
  getParentRoute: () => StudiosStudioIdRouteRoute,
} as any)
const StudiosStudioIdMyCompensationsRoute =
  StudiosStudioIdMyCompensationsRouteImport.update({
    id: '/my-compensations',
    path: '/my-compensations',
    getParentRoute: () => StudiosStudioIdRouteRoute,
  } as any)
const StudiosStudioIdMembersRoute = StudiosStudioIdMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => StudiosStudioIdRouteRoute,
} as any)
const StudiosStudioIdDashboardRoute =
  StudiosStudioIdDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => StudiosStudioIdRouteRoute,
  } as any)
const StudiosStudioIdCreatorsRoute = StudiosStudioIdCreatorsRouteImport.update({
  id: '/creators',
  path: '/creators',
  getParentRoute: () => StudiosStudioIdRouteRoute,
} as any)
const StudiosStudioIdCreatorMappingRoute =
  StudiosStudioIdCreatorMappingRouteImport.update({
    id: '/creator-mapping',
    path: '/creator-mapping',
    getParentRoute: () => StudiosStudioIdRouteRoute,
  } as any)
const StudiosStudioIdCostsRoute = StudiosStudioIdCostsRouteImport.update({
  id: '/costs',
  path: '/costs',
  getParentRoute: () => StudiosStudioIdRouteRoute,
} as any)
const StudiosStudioIdTaskTemplatesIndexRoute =
  StudiosStudioIdTaskTemplatesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => StudiosStudioIdTaskTemplatesRoute,
  } as any)
const StudiosStudioIdTaskSetupIndexRoute =
  StudiosStudioIdTaskSetupIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => StudiosStudioIdTaskSetupRoute,
  } as any)
const StudiosStudioIdTaskReviewIndexRoute =
  StudiosStudioIdTaskReviewIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => StudiosStudioIdTaskReviewRoute,
  } as any)
const StudiosStudioIdTaskReportsIndexRoute =
  StudiosStudioIdTaskReportsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => StudiosStudioIdTaskReportsRoute,
  } as any)
const StudiosStudioIdShowsIndexRoute =
  StudiosStudioIdShowsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => StudiosStudioIdShowsRoute,
  } as any)
const StudiosStudioIdShiftsIndexRoute =
  StudiosStudioIdShiftsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => StudiosStudioIdShiftsRoute,
  } as any)
const StudiosStudioIdMembersIndexRoute =
  StudiosStudioIdMembersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => StudiosStudioIdMembersRoute,
  } as any)
const StudiosStudioIdCreatorsIndexRoute =
  StudiosStudioIdCreatorsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => StudiosStudioIdCreatorsRoute,
  } as any)
const StudiosStudioIdCreatorMappingIndexRoute =
  StudiosStudioIdCreatorMappingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => StudiosStudioIdCreatorMappingRoute,
  } as any)
const SystemShowsShowIdTasksRoute = SystemShowsShowIdTasksRouteImport.update({
  id: '/shows/$showId/tasks',
  path: '/shows/$showId/tasks',
  getParentRoute: () => SystemRouteRoute,
} as any)
const StudiosStudioIdTaskTemplatesNewRoute =
  StudiosStudioIdTaskTemplatesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => StudiosStudioIdTaskTemplatesRoute,
  } as any)
const StudiosStudioIdTaskTemplatesTemplateIdRoute =
  StudiosStudioIdTaskTemplatesTemplateIdRouteImport.update({
    id: '/$templateId',
    path: '/$templateId',
    getParentRoute: () => StudiosStudioIdTaskTemplatesRoute,
  } as any)
const StudiosStudioIdTaskReportsResultsRoute =
  StudiosStudioIdTaskReportsResultsRouteImport.update({
    id: '/results',
    path: '/results',
    getParentRoute: () => StudiosStudioIdTaskReportsRoute,
  } as any)
const StudiosStudioIdTaskReportsBuilderRoute =
  StudiosStudioIdTaskReportsBuilderRouteImport.update({
    id: '/builder',
    path: '/builder',
    getParentRoute: () => StudiosStudioIdTaskReportsRoute,
  } as any)
const StudiosStudioIdShowsShowIdRouteRoute =
  StudiosStudioIdShowsShowIdRouteRouteImport.update({
    id: '/$showId',
    path: '/$showId',
    getParentRoute: () => StudiosStudioIdShowsRoute,
  } as any)
const StudiosStudioIdShiftsShiftIdRouteRoute =
  StudiosStudioIdShiftsShiftIdRouteRouteImport.update({
    id: '/$shiftId',
    path: '/$shiftId',
    getParentRoute: () => StudiosStudioIdShiftsRoute,
  } as any)
const StudiosStudioIdMembersMemberIdRouteRoute =
  StudiosStudioIdMembersMemberIdRouteRouteImport.update({
    id: '/$memberId',
    path: '/$memberId',
    getParentRoute: () => StudiosStudioIdMembersRoute,
  } as any)
const StudiosStudioIdCreatorsCreatorIdRouteRoute =
  StudiosStudioIdCreatorsCreatorIdRouteRouteImport.update({
    id: '/$creatorId',
    path: '/$creatorId',
    getParentRoute: () => StudiosStudioIdCreatorsRoute,
  } as any)
const SystemStudiosStudioIdStudioRoomsIndexRoute =
  SystemStudiosStudioIdStudioRoomsIndexRouteImport.update({
    id: '/studios/$studioId/studio-rooms/',
    path: '/studios/$studioId/studio-rooms/',
    getParentRoute: () => SystemRouteRoute,
  } as any)
const SystemSchedulesScheduleIdSnapshotsIndexRoute =
  SystemSchedulesScheduleIdSnapshotsIndexRouteImport.update({
    id: '/schedules/$scheduleId/snapshots/',
    path: '/schedules/$scheduleId/snapshots/',
    getParentRoute: () => SystemRouteRoute,
  } as any)
const StudiosStudioIdShowsShowIdIndexRoute =
  StudiosStudioIdShowsShowIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => StudiosStudioIdShowsShowIdRouteRoute,
  } as any)
const StudiosStudioIdShiftsShiftIdIndexRoute =
  StudiosStudioIdShiftsShiftIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => StudiosStudioIdShiftsShiftIdRouteRoute,
  } as any)
const StudiosStudioIdMembersMemberIdIndexRoute =
  StudiosStudioIdMembersMemberIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => StudiosStudioIdMembersMemberIdRouteRoute,
  } as any)
const StudiosStudioIdCreatorsCreatorIdIndexRoute =
  StudiosStudioIdCreatorsCreatorIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => StudiosStudioIdCreatorsCreatorIdRouteRoute,
  } as any)
const StudiosStudioIdShowsShowIdTasksRoute =
  StudiosStudioIdShowsShowIdTasksRouteImport.update({
    id: '/tasks',
    path: '/tasks',
    getParentRoute: () => StudiosStudioIdShowsShowIdRouteRoute,
  } as any)
const StudiosStudioIdShowsShowIdPerformanceRoute =
  StudiosStudioIdShowsShowIdPerformanceRouteImport.update({
    id: '/performance',
    path: '/performance',
    getParentRoute: () => StudiosStudioIdShowsShowIdRouteRoute,
  } as any)
const StudiosStudioIdShowsShowIdCompensationRoute =
  StudiosStudioIdShowsShowIdCompensationRouteImport.update({
    id: '/compensation',
    path: '/compensation',
    getParentRoute: () => StudiosStudioIdShowsShowIdRouteRoute,
  } as any)
const StudiosStudioIdShowsShowIdActualsRoute =
  StudiosStudioIdShowsShowIdActualsRouteImport.update({
    id: '/actuals',
    path: '/actuals',
    getParentRoute: () => StudiosStudioIdShowsShowIdRouteRoute,
  } as any)
const StudiosStudioIdShiftsShiftIdCompensationRoute =
  StudiosStudioIdShiftsShiftIdCompensationRouteImport.update({
    id: '/compensation',
    path: '/compensation',
    getParentRoute: () => StudiosStudioIdShiftsShiftIdRouteRoute,
  } as any)
const StudiosStudioIdMembersMemberIdCompensationsRoute =
  StudiosStudioIdMembersMemberIdCompensationsRouteImport.update({
    id: '/compensations',
    path: '/compensations',
    getParentRoute: () => StudiosStudioIdMembersMemberIdRouteRoute,
  } as any)
const StudiosStudioIdCreatorsCreatorIdCompensationsRoute =
  StudiosStudioIdCreatorsCreatorIdCompensationsRouteImport.update({
    id: '/compensations',
    path: '/compensations',
    getParentRoute: () => StudiosStudioIdCreatorsCreatorIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/studios': typeof StudiosRouteRouteWithChildren
  '/system': typeof SystemRouteRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/settings': typeof SettingsRoute
  '/studios/$studioId': typeof StudiosStudioIdRouteRouteWithChildren
  '/studios/$studioId/costs': typeof StudiosStudioIdCostsRoute
  '/studios/$studioId/creator-mapping': typeof StudiosStudioIdCreatorMappingRouteWithChildren
  '/studios/$studioId/creators': typeof StudiosStudioIdCreatorsRouteWithChildren
  '/studios/$studioId/dashboard': typeof StudiosStudioIdDashboardRoute
  '/studios/$studioId/members': typeof StudiosStudioIdMembersRouteWithChildren
  '/studios/$studioId/my-compensations': typeof StudiosStudioIdMyCompensationsRoute
  '/studios/$studioId/my-shifts': typeof StudiosStudioIdMyShiftsRoute
  '/studios/$studioId/my-tasks': typeof StudiosStudioIdMyTasksRoute
  '/studios/$studioId/performance': typeof StudiosStudioIdPerformanceRoute
  '/studios/$studioId/shared-fields': typeof StudiosStudioIdSharedFieldsRoute
  '/studios/$studioId/shifts': typeof StudiosStudioIdShiftsRouteWithChildren
  '/studios/$studioId/show-run-review': typeof StudiosStudioIdShowRunReviewRoute
  '/studios/$studioId/shows': typeof StudiosStudioIdShowsRouteWithChildren
  '/studios/$studioId/task-reports': typeof StudiosStudioIdTaskReportsRouteWithChildren
  '/studios/$studioId/task-review': typeof StudiosStudioIdTaskReviewRouteWithChildren
  '/studios/$studioId/task-setup': typeof StudiosStudioIdTaskSetupRouteWithChildren
  '/studios/$studioId/task-templates': typeof StudiosStudioIdTaskTemplatesRouteWithChildren
  '/system/clients': typeof SystemClientsIndexRoute
  '/system/compensation-line-items': typeof SystemCompensationLineItemsIndexRoute
  '/system/creators': typeof SystemCreatorsIndexRoute
  '/system/memberships': typeof SystemMembershipsIndexRoute
  '/system/platforms': typeof SystemPlatformsIndexRoute
  '/system/schedules': typeof SystemSchedulesIndexRoute
  '/system/show-standards': typeof SystemShowStandardsIndexRoute
  '/system/show-statuses': typeof SystemShowStatusesIndexRoute
  '/system/show-types': typeof SystemShowTypesIndexRoute
  '/system/shows': typeof SystemShowsIndexRoute
  '/system/studios': typeof SystemStudiosIndexRoute
  '/system/task-templates': typeof SystemTaskTemplatesIndexRoute
  '/system/tasks': typeof SystemTasksIndexRoute
  '/system/users': typeof SystemUsersIndexRoute
  '/studios/$studioId/creators/$creatorId': typeof StudiosStudioIdCreatorsCreatorIdRouteRouteWithChildren
  '/studios/$studioId/members/$memberId': typeof StudiosStudioIdMembersMemberIdRouteRouteWithChildren
  '/studios/$studioId/shifts/$shiftId': typeof StudiosStudioIdShiftsShiftIdRouteRouteWithChildren
  '/studios/$studioId/shows/$showId': typeof StudiosStudioIdShowsShowIdRouteRouteWithChildren
  '/studios/$studioId/task-reports/builder': typeof StudiosStudioIdTaskReportsBuilderRoute
  '/studios/$studioId/task-reports/results': typeof StudiosStudioIdTaskReportsResultsRoute
  '/studios/$studioId/task-templates/$templateId': typeof StudiosStudioIdTaskTemplatesTemplateIdRoute
  '/studios/$studioId/task-templates/new': typeof StudiosStudioIdTaskTemplatesNewRoute
  '/system/shows/$showId/tasks': typeof SystemShowsShowIdTasksRoute
  '/studios/$studioId/creator-mapping/': typeof StudiosStudioIdCreatorMappingIndexRoute
  '/studios/$studioId/creators/': typeof StudiosStudioIdCreatorsIndexRoute
  '/studios/$studioId/members/': typeof StudiosStudioIdMembersIndexRoute
  '/studios/$studioId/shifts/': typeof StudiosStudioIdShiftsIndexRoute
  '/studios/$studioId/shows/': typeof StudiosStudioIdShowsIndexRoute
  '/studios/$studioId/task-reports/': typeof StudiosStudioIdTaskReportsIndexRoute
  '/studios/$studioId/task-review/': typeof StudiosStudioIdTaskReviewIndexRoute
  '/studios/$studioId/task-setup/': typeof StudiosStudioIdTaskSetupIndexRoute
  '/studios/$studioId/task-templates/': typeof StudiosStudioIdTaskTemplatesIndexRoute
  '/studios/$studioId/creators/$creatorId/compensations': typeof StudiosStudioIdCreatorsCreatorIdCompensationsRoute
  '/studios/$studioId/members/$memberId/compensations': typeof StudiosStudioIdMembersMemberIdCompensationsRoute
  '/studios/$studioId/shifts/$shiftId/compensation': typeof StudiosStudioIdShiftsShiftIdCompensationRoute
  '/studios/$studioId/shows/$showId/actuals': typeof StudiosStudioIdShowsShowIdActualsRoute
  '/studios/$studioId/shows/$showId/compensation': typeof StudiosStudioIdShowsShowIdCompensationRoute
  '/studios/$studioId/shows/$showId/performance': typeof StudiosStudioIdShowsShowIdPerformanceRoute
  '/studios/$studioId/shows/$showId/tasks': typeof StudiosStudioIdShowsShowIdTasksRoute
  '/studios/$studioId/creators/$creatorId/': typeof StudiosStudioIdCreatorsCreatorIdIndexRoute
  '/studios/$studioId/members/$memberId/': typeof StudiosStudioIdMembersMemberIdIndexRoute
  '/studios/$studioId/shifts/$shiftId/': typeof StudiosStudioIdShiftsShiftIdIndexRoute
  '/studios/$studioId/shows/$showId/': typeof StudiosStudioIdShowsShowIdIndexRoute
  '/system/schedules/$scheduleId/snapshots': typeof SystemSchedulesScheduleIdSnapshotsIndexRoute
  '/system/studios/$studioId/studio-rooms': typeof SystemStudiosStudioIdStudioRoomsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/studios': typeof StudiosRouteRouteWithChildren
  '/system': typeof SystemRouteRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/settings': typeof SettingsRoute
  '/studios/$studioId': typeof StudiosStudioIdRouteRouteWithChildren
  '/studios/$studioId/costs': typeof StudiosStudioIdCostsRoute
  '/studios/$studioId/dashboard': typeof StudiosStudioIdDashboardRoute
  '/studios/$studioId/my-compensations': typeof StudiosStudioIdMyCompensationsRoute
  '/studios/$studioId/my-shifts': typeof StudiosStudioIdMyShiftsRoute
  '/studios/$studioId/my-tasks': typeof StudiosStudioIdMyTasksRoute
  '/studios/$studioId/performance': typeof StudiosStudioIdPerformanceRoute
  '/studios/$studioId/shared-fields': typeof StudiosStudioIdSharedFieldsRoute
  '/studios/$studioId/show-run-review': typeof StudiosStudioIdShowRunReviewRoute
  '/system/clients': typeof SystemClientsIndexRoute
  '/system/compensation-line-items': typeof SystemCompensationLineItemsIndexRoute
  '/system/creators': typeof SystemCreatorsIndexRoute
  '/system/memberships': typeof SystemMembershipsIndexRoute
  '/system/platforms': typeof SystemPlatformsIndexRoute
  '/system/schedules': typeof SystemSchedulesIndexRoute
  '/system/show-standards': typeof SystemShowStandardsIndexRoute
  '/system/show-statuses': typeof SystemShowStatusesIndexRoute
  '/system/show-types': typeof SystemShowTypesIndexRoute
  '/system/shows': typeof SystemShowsIndexRoute
  '/system/studios': typeof SystemStudiosIndexRoute
  '/system/task-templates': typeof SystemTaskTemplatesIndexRoute
  '/system/tasks': typeof SystemTasksIndexRoute
  '/system/users': typeof SystemUsersIndexRoute
  '/studios/$studioId/task-reports/builder': typeof StudiosStudioIdTaskReportsBuilderRoute
  '/studios/$studioId/task-reports/results': typeof StudiosStudioIdTaskReportsResultsRoute
  '/studios/$studioId/task-templates/$templateId': typeof StudiosStudioIdTaskTemplatesTemplateIdRoute
  '/studios/$studioId/task-templates/new': typeof StudiosStudioIdTaskTemplatesNewRoute
  '/system/shows/$showId/tasks': typeof SystemShowsShowIdTasksRoute
  '/studios/$studioId/creator-mapping': typeof StudiosStudioIdCreatorMappingIndexRoute
  '/studios/$studioId/creators': typeof StudiosStudioIdCreatorsIndexRoute
  '/studios/$studioId/members': typeof StudiosStudioIdMembersIndexRoute
  '/studios/$studioId/shifts': typeof StudiosStudioIdShiftsIndexRoute
  '/studios/$studioId/shows': typeof StudiosStudioIdShowsIndexRoute
  '/studios/$studioId/task-reports': typeof StudiosStudioIdTaskReportsIndexRoute
  '/studios/$studioId/task-review': typeof StudiosStudioIdTaskReviewIndexRoute
  '/studios/$studioId/task-setup': typeof StudiosStudioIdTaskSetupIndexRoute
  '/studios/$studioId/task-templates': typeof StudiosStudioIdTaskTemplatesIndexRoute
  '/studios/$studioId/creators/$creatorId/compensations': typeof StudiosStudioIdCreatorsCreatorIdCompensationsRoute
  '/studios/$studioId/members/$memberId/compensations': typeof StudiosStudioIdMembersMemberIdCompensationsRoute
  '/studios/$studioId/shifts/$shiftId/compensation': typeof StudiosStudioIdShiftsShiftIdCompensationRoute
  '/studios/$studioId/shows/$showId/actuals': typeof StudiosStudioIdShowsShowIdActualsRoute
  '/studios/$studioId/shows/$showId/compensation': typeof StudiosStudioIdShowsShowIdCompensationRoute
  '/studios/$studioId/shows/$showId/performance': typeof StudiosStudioIdShowsShowIdPerformanceRoute
  '/studios/$studioId/shows/$showId/tasks': typeof StudiosStudioIdShowsShowIdTasksRoute
  '/studios/$studioId/creators/$creatorId': typeof StudiosStudioIdCreatorsCreatorIdIndexRoute
  '/studios/$studioId/members/$memberId': typeof StudiosStudioIdMembersMemberIdIndexRoute
  '/studios/$studioId/shifts/$shiftId': typeof StudiosStudioIdShiftsShiftIdIndexRoute
  '/studios/$studioId/shows/$showId': typeof StudiosStudioIdShowsShowIdIndexRoute
  '/system/schedules/$scheduleId/snapshots': typeof SystemSchedulesScheduleIdSnapshotsIndexRoute
  '/system/studios/$studioId/studio-rooms': typeof SystemStudiosStudioIdStudioRoomsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/studios': typeof StudiosRouteRouteWithChildren
  '/system': typeof SystemRouteRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/settings': typeof SettingsRoute
  '/studios/$studioId': typeof StudiosStudioIdRouteRouteWithChildren
  '/studios/$studioId/costs': typeof StudiosStudioIdCostsRoute
  '/studios/$studioId/creator-mapping': typeof StudiosStudioIdCreatorMappingRouteWithChildren
  '/studios/$studioId/creators': typeof StudiosStudioIdCreatorsRouteWithChildren
  '/studios/$studioId/dashboard': typeof StudiosStudioIdDashboardRoute
  '/studios/$studioId/members': typeof StudiosStudioIdMembersRouteWithChildren
  '/studios/$studioId/my-compensations': typeof StudiosStudioIdMyCompensationsRoute
  '/studios/$studioId/my-shifts': typeof StudiosStudioIdMyShiftsRoute
  '/studios/$studioId/my-tasks': typeof StudiosStudioIdMyTasksRoute
  '/studios/$studioId/performance': typeof StudiosStudioIdPerformanceRoute
  '/studios/$studioId/shared-fields': typeof StudiosStudioIdSharedFieldsRoute
  '/studios/$studioId/shifts': typeof StudiosStudioIdShiftsRouteWithChildren
  '/studios/$studioId/show-run-review': typeof StudiosStudioIdShowRunReviewRoute
  '/studios/$studioId/shows': typeof StudiosStudioIdShowsRouteWithChildren
  '/studios/$studioId/task-reports': typeof StudiosStudioIdTaskReportsRouteWithChildren
  '/studios/$studioId/task-review': typeof StudiosStudioIdTaskReviewRouteWithChildren
  '/studios/$studioId/task-setup': typeof StudiosStudioIdTaskSetupRouteWithChildren
  '/studios/$studioId/task-templates': typeof StudiosStudioIdTaskTemplatesRouteWithChildren
  '/system/clients/': typeof SystemClientsIndexRoute
  '/system/compensation-line-items/': typeof SystemCompensationLineItemsIndexRoute
  '/system/creators/': typeof SystemCreatorsIndexRoute
  '/system/memberships/': typeof SystemMembershipsIndexRoute
  '/system/platforms/': typeof SystemPlatformsIndexRoute
  '/system/schedules/': typeof SystemSchedulesIndexRoute
  '/system/show-standards/': typeof SystemShowStandardsIndexRoute
  '/system/show-statuses/': typeof SystemShowStatusesIndexRoute
  '/system/show-types/': typeof SystemShowTypesIndexRoute
  '/system/shows/': typeof SystemShowsIndexRoute
  '/system/studios/': typeof SystemStudiosIndexRoute
  '/system/task-templates/': typeof SystemTaskTemplatesIndexRoute
  '/system/tasks/': typeof SystemTasksIndexRoute
  '/system/users/': typeof SystemUsersIndexRoute
  '/studios/$studioId/creators/$creatorId': typeof StudiosStudioIdCreatorsCreatorIdRouteRouteWithChildren
  '/studios/$studioId/members/$memberId': typeof StudiosStudioIdMembersMemberIdRouteRouteWithChildren
  '/studios/$studioId/shifts/$shiftId': typeof StudiosStudioIdShiftsShiftIdRouteRouteWithChildren
  '/studios/$studioId/shows/$showId': typeof StudiosStudioIdShowsShowIdRouteRouteWithChildren
  '/studios/$studioId/task-reports/builder': typeof StudiosStudioIdTaskReportsBuilderRoute
  '/studios/$studioId/task-reports/results': typeof StudiosStudioIdTaskReportsResultsRoute
  '/studios/$studioId/task-templates/$templateId': typeof StudiosStudioIdTaskTemplatesTemplateIdRoute
  '/studios/$studioId/task-templates/new': typeof StudiosStudioIdTaskTemplatesNewRoute
  '/system/shows/$showId/tasks': typeof SystemShowsShowIdTasksRoute
  '/studios/$studioId/creator-mapping/': typeof StudiosStudioIdCreatorMappingIndexRoute
  '/studios/$studioId/creators/': typeof StudiosStudioIdCreatorsIndexRoute
  '/studios/$studioId/members/': typeof StudiosStudioIdMembersIndexRoute
  '/studios/$studioId/shifts/': typeof StudiosStudioIdShiftsIndexRoute
  '/studios/$studioId/shows/': typeof StudiosStudioIdShowsIndexRoute
  '/studios/$studioId/task-reports/': typeof StudiosStudioIdTaskReportsIndexRoute
  '/studios/$studioId/task-review/': typeof StudiosStudioIdTaskReviewIndexRoute
  '/studios/$studioId/task-setup/': typeof StudiosStudioIdTaskSetupIndexRoute
  '/studios/$studioId/task-templates/': typeof StudiosStudioIdTaskTemplatesIndexRoute
  '/studios/$studioId/creators/$creatorId/compensations': typeof StudiosStudioIdCreatorsCreatorIdCompensationsRoute
  '/studios/$studioId/members/$memberId/compensations': typeof StudiosStudioIdMembersMemberIdCompensationsRoute
  '/studios/$studioId/shifts/$shiftId/compensation': typeof StudiosStudioIdShiftsShiftIdCompensationRoute
  '/studios/$studioId/shows/$showId/actuals': typeof StudiosStudioIdShowsShowIdActualsRoute
  '/studios/$studioId/shows/$showId/compensation': typeof StudiosStudioIdShowsShowIdCompensationRoute
  '/studios/$studioId/shows/$showId/performance': typeof StudiosStudioIdShowsShowIdPerformanceRoute
  '/studios/$studioId/shows/$showId/tasks': typeof StudiosStudioIdShowsShowIdTasksRoute
  '/studios/$studioId/creators/$creatorId/': typeof StudiosStudioIdCreatorsCreatorIdIndexRoute
  '/studios/$studioId/members/$memberId/': typeof StudiosStudioIdMembersMemberIdIndexRoute
  '/studios/$studioId/shifts/$shiftId/': typeof StudiosStudioIdShiftsShiftIdIndexRoute
  '/studios/$studioId/shows/$showId/': typeof StudiosStudioIdShowsShowIdIndexRoute
  '/system/schedules/$scheduleId/snapshots/': typeof SystemSchedulesScheduleIdSnapshotsIndexRoute
  '/system/studios/$studioId/studio-rooms/': typeof SystemStudiosStudioIdStudioRoomsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/studios'
    | '/system'
    | '/dashboard'
    | '/settings'
    | '/studios/$studioId'
    | '/studios/$studioId/costs'
    | '/studios/$studioId/creator-mapping'
    | '/studios/$studioId/creators'
    | '/studios/$studioId/dashboard'
    | '/studios/$studioId/members'
    | '/studios/$studioId/my-compensations'
    | '/studios/$studioId/my-shifts'
    | '/studios/$studioId/my-tasks'
    | '/studios/$studioId/performance'
    | '/studios/$studioId/shared-fields'
    | '/studios/$studioId/shifts'
    | '/studios/$studioId/show-run-review'
    | '/studios/$studioId/shows'
    | '/studios/$studioId/task-reports'
    | '/studios/$studioId/task-review'
    | '/studios/$studioId/task-setup'
    | '/studios/$studioId/task-templates'
    | '/system/clients'
    | '/system/compensation-line-items'
    | '/system/creators'
    | '/system/memberships'
    | '/system/platforms'
    | '/system/schedules'
    | '/system/show-standards'
    | '/system/show-statuses'
    | '/system/show-types'
    | '/system/shows'
    | '/system/studios'
    | '/system/task-templates'
    | '/system/tasks'
    | '/system/users'
    | '/studios/$studioId/creators/$creatorId'
    | '/studios/$studioId/members/$memberId'
    | '/studios/$studioId/shifts/$shiftId'
    | '/studios/$studioId/shows/$showId'
    | '/studios/$studioId/task-reports/builder'
    | '/studios/$studioId/task-reports/results'
    | '/studios/$studioId/task-templates/$templateId'
    | '/studios/$studioId/task-templates/new'
    | '/system/shows/$showId/tasks'
    | '/studios/$studioId/creator-mapping/'
    | '/studios/$studioId/creators/'
    | '/studios/$studioId/members/'
    | '/studios/$studioId/shifts/'
    | '/studios/$studioId/shows/'
    | '/studios/$studioId/task-reports/'
    | '/studios/$studioId/task-review/'
    | '/studios/$studioId/task-setup/'
    | '/studios/$studioId/task-templates/'
    | '/studios/$studioId/creators/$creatorId/compensations'
    | '/studios/$studioId/members/$memberId/compensations'
    | '/studios/$studioId/shifts/$shiftId/compensation'
    | '/studios/$studioId/shows/$showId/actuals'
    | '/studios/$studioId/shows/$showId/compensation'
    | '/studios/$studioId/shows/$showId/performance'
    | '/studios/$studioId/shows/$showId/tasks'
    | '/studios/$studioId/creators/$creatorId/'
    | '/studios/$studioId/members/$memberId/'
    | '/studios/$studioId/shifts/$shiftId/'
    | '/studios/$studioId/shows/$showId/'
    | '/system/schedules/$scheduleId/snapshots'
    | '/system/studios/$studioId/studio-rooms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/studios'
    | '/system'
    | '/dashboard'
    | '/settings'
    | '/studios/$studioId'
    | '/studios/$studioId/costs'
    | '/studios/$studioId/dashboard'
    | '/studios/$studioId/my-compensations'
    | '/studios/$studioId/my-shifts'
    | '/studios/$studioId/my-tasks'
    | '/studios/$studioId/performance'
    | '/studios/$studioId/shared-fields'
    | '/studios/$studioId/show-run-review'
    | '/system/clients'
    | '/system/compensation-line-items'
    | '/system/creators'
    | '/system/memberships'
    | '/system/platforms'
    | '/system/schedules'
    | '/system/show-standards'
    | '/system/show-statuses'
    | '/system/show-types'
    | '/system/shows'
    | '/system/studios'
    | '/system/task-templates'
    | '/system/tasks'
    | '/system/users'
    | '/studios/$studioId/task-reports/builder'
    | '/studios/$studioId/task-reports/results'
    | '/studios/$studioId/task-templates/$templateId'
    | '/studios/$studioId/task-templates/new'
    | '/system/shows/$showId/tasks'
    | '/studios/$studioId/creator-mapping'
    | '/studios/$studioId/creators'
    | '/studios/$studioId/members'
    | '/studios/$studioId/shifts'
    | '/studios/$studioId/shows'
    | '/studios/$studioId/task-reports'
    | '/studios/$studioId/task-review'
    | '/studios/$studioId/task-setup'
    | '/studios/$studioId/task-templates'
    | '/studios/$studioId/creators/$creatorId/compensations'
    | '/studios/$studioId/members/$memberId/compensations'
    | '/studios/$studioId/shifts/$shiftId/compensation'
    | '/studios/$studioId/shows/$showId/actuals'
    | '/studios/$studioId/shows/$showId/compensation'
    | '/studios/$studioId/shows/$showId/performance'
    | '/studios/$studioId/shows/$showId/tasks'
    | '/studios/$studioId/creators/$creatorId'
    | '/studios/$studioId/members/$memberId'
    | '/studios/$studioId/shifts/$shiftId'
    | '/studios/$studioId/shows/$showId'
    | '/system/schedules/$scheduleId/snapshots'
    | '/system/studios/$studioId/studio-rooms'
  id:
    | '__root__'
    | '/'
    | '/studios'
    | '/system'
    | '/dashboard'
    | '/settings'
    | '/studios/$studioId'
    | '/studios/$studioId/costs'
    | '/studios/$studioId/creator-mapping'
    | '/studios/$studioId/creators'
    | '/studios/$studioId/dashboard'
    | '/studios/$studioId/members'
    | '/studios/$studioId/my-compensations'
    | '/studios/$studioId/my-shifts'
    | '/studios/$studioId/my-tasks'
    | '/studios/$studioId/performance'
    | '/studios/$studioId/shared-fields'
    | '/studios/$studioId/shifts'
    | '/studios/$studioId/show-run-review'
    | '/studios/$studioId/shows'
    | '/studios/$studioId/task-reports'
    | '/studios/$studioId/task-review'
    | '/studios/$studioId/task-setup'
    | '/studios/$studioId/task-templates'
    | '/system/clients/'
    | '/system/compensation-line-items/'
    | '/system/creators/'
    | '/system/memberships/'
    | '/system/platforms/'
    | '/system/schedules/'
    | '/system/show-standards/'
    | '/system/show-statuses/'
    | '/system/show-types/'
    | '/system/shows/'
    | '/system/studios/'
    | '/system/task-templates/'
    | '/system/tasks/'
    | '/system/users/'
    | '/studios/$studioId/creators/$creatorId'
    | '/studios/$studioId/members/$memberId'
    | '/studios/$studioId/shifts/$shiftId'
    | '/studios/$studioId/shows/$showId'
    | '/studios/$studioId/task-reports/builder'
    | '/studios/$studioId/task-reports/results'
    | '/studios/$studioId/task-templates/$templateId'
    | '/studios/$studioId/task-templates/new'
    | '/system/shows/$showId/tasks'
    | '/studios/$studioId/creator-mapping/'
    | '/studios/$studioId/creators/'
    | '/studios/$studioId/members/'
    | '/studios/$studioId/shifts/'
    | '/studios/$studioId/shows/'
    | '/studios/$studioId/task-reports/'
    | '/studios/$studioId/task-review/'
    | '/studios/$studioId/task-setup/'
    | '/studios/$studioId/task-templates/'
    | '/studios/$studioId/creators/$creatorId/compensations'
    | '/studios/$studioId/members/$memberId/compensations'
    | '/studios/$studioId/shifts/$shiftId/compensation'
    | '/studios/$studioId/shows/$showId/actuals'
    | '/studios/$studioId/shows/$showId/compensation'
    | '/studios/$studioId/shows/$showId/performance'
    | '/studios/$studioId/shows/$showId/tasks'
    | '/studios/$studioId/creators/$creatorId/'
    | '/studios/$studioId/members/$memberId/'
    | '/studios/$studioId/shifts/$shiftId/'
    | '/studios/$studioId/shows/$showId/'
    | '/system/schedules/$scheduleId/snapshots/'
    | '/system/studios/$studioId/studio-rooms/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StudiosRouteRoute: typeof StudiosRouteRouteWithChildren
  SystemRouteRoute: typeof SystemRouteRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studios': {
      id: '/studios'
      path: '/studios'
      fullPath: '/studios'
      preLoaderRoute: typeof StudiosRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studios/$studioId': {
      id: '/studios/$studioId'
      path: '/$studioId'
      fullPath: '/studios/$studioId'
      preLoaderRoute: typeof StudiosStudioIdRouteRouteImport
      parentRoute: typeof StudiosRouteRoute
    }
    '/system/users/': {
      id: '/system/users/'
      path: '/users'
      fullPath: '/system/users'
      preLoaderRoute: typeof SystemUsersIndexRouteImport
      parentRoute: typeof SystemRouteRoute
    }
    '/system/tasks/': {
      id: '/system/tasks/'
      path: '/tasks'
      fullPath: '/system/tasks'
      preLoaderRoute: typeof SystemTasksIndexRouteImport
      parentRoute: typeof SystemRouteRoute
    }
    '/system/task-templates/': {
      id: '/system/task-templates/'
      path: '/task-templates'
      fullPath: '/system/task-templates'
      preLoaderRoute: typeof SystemTaskTemplatesIndexRouteImport
      parentRoute: typeof SystemRouteRoute
    }
    '/system/studios/': {
      id: '/system/studios/'
      path: '/studios'
      fullPath: '/system/studios'
      preLoaderRoute: typeof SystemStudiosIndexRouteImport
      parentRoute: typeof SystemRouteRoute
    }
    '/system/shows/': {
      id: '/system/shows/'
      path: '/shows'
      fullPath: '/system/shows'
      preLoaderRoute: typeof SystemShowsIndexRouteImport
      parentRoute: typeof SystemRouteRoute
    }
    '/system/show-types/': {
      id: '/system/show-types/'
      path: '/show-types'
      fullPath: '/system/show-types'
      preLoaderRoute: typeof SystemShowTypesIndexRouteImport
      parentRoute: typeof SystemRouteRoute
    }
    '/system/show-statuses/': {
      id: '/system/show-statuses/'
      path: '/show-statuses'
      fullPath: '/system/show-statuses'
      preLoaderRoute: typeof SystemShowStatusesIndexRouteImport
      parentRoute: typeof SystemRouteRoute
    }
    '/system/show-standards/': {
      id: '/system/show-standards/'
      path: '/show-standards'
      fullPath: '/system/show-standards'
      preLoaderRoute: typeof SystemShowStandardsIndexRouteImport
      parentRoute: typeof SystemRouteRoute
    }
    '/system/schedules/': {
      id: '/system/schedules/'
      path: '/schedules'
      fullPath: '/system/schedules'
      preLoaderRoute: typeof SystemSchedulesIndexRouteImport
      parentRoute: typeof SystemRouteRoute
    }
    '/system/platforms/': {
      id: '/system/platforms/'
      path: '/platforms'
      fullPath: '/system/platforms'
      preLoaderRoute: typeof SystemPlatformsIndexRouteImport
      parentRoute: typeof SystemRouteRoute
    }
    '/system/memberships/': {
      id: '/system/memberships/'
      path: '/memberships'
      fullPath: '/system/memberships'
      preLoaderRoute: typeof SystemMembershipsIndexRouteImport
      parentRoute: typeof SystemRouteRoute
    }
    '/system/creators/': {
      id: '/system/creators/'
      path: '/creators'
      fullPath: '/system/creators'
      preLoaderRoute: typeof SystemCreatorsIndexRouteImport
      parentRoute: typeof SystemRouteRoute
    }
    '/system/compensation-line-items/': {
      id: '/system/compensation-line-items/'
      path: '/compensation-line-items'
      fullPath: '/system/compensation-line-items'
      preLoaderRoute: typeof SystemCompensationLineItemsIndexRouteImport
      parentRoute: typeof SystemRouteRoute
    }
    '/system/clients/': {
      id: '/system/clients/'
      path: '/clients'
      fullPath: '/system/clients'
      preLoaderRoute: typeof SystemClientsIndexRouteImport
      parentRoute: typeof SystemRouteRoute
    }
    '/studios/$studioId/task-templates': {
      id: '/studios/$studioId/task-templates'
      path: '/task-templates'
      fullPath: '/studios/$studioId/task-templates'
      preLoaderRoute: typeof StudiosStudioIdTaskTemplatesRouteImport
      parentRoute: typeof StudiosStudioIdRouteRoute
    }
    '/studios/$studioId/task-setup': {
      id: '/studios/$studioId/task-setup'
      path: '/task-setup'
      fullPath: '/studios/$studioId/task-setup'
      preLoaderRoute: typeof StudiosStudioIdTaskSetupRouteImport
      parentRoute: typeof StudiosStudioIdRouteRoute
    }
    '/studios/$studioId/task-review': {
      id: '/studios/$studioId/task-review'
      path: '/task-review'
      fullPath: '/studios/$studioId/task-review'
      preLoaderRoute: typeof StudiosStudioIdTaskReviewRouteImport
      parentRoute: typeof StudiosStudioIdRouteRoute
    }
    '/studios/$studioId/task-reports': {
      id: '/studios/$studioId/task-reports'
      path: '/task-reports'
      fullPath: '/studios/$studioId/task-reports'
      preLoaderRoute: typeof StudiosStudioIdTaskReportsRouteImport
      parentRoute: typeof StudiosStudioIdRouteRoute
    }
    '/studios/$studioId/shows': {
      id: '/studios/$studioId/shows'
      path: '/shows'
      fullPath: '/studios/$studioId/shows'
      preLoaderRoute: typeof StudiosStudioIdShowsRouteImport
      parentRoute: typeof StudiosStudioIdRouteRoute
    }
    '/studios/$studioId/show-run-review': {
      id: '/studios/$studioId/show-run-review'
      path: '/show-run-review'
      fullPath: '/studios/$studioId/show-run-review'
      preLoaderRoute: typeof StudiosStudioIdShowRunReviewRouteImport
      parentRoute: typeof StudiosStudioIdRouteRoute
    }
    '/studios/$studioId/shifts': {
      id: '/studios/$studioId/shifts'
      path: '/shifts'
      fullPath: '/studios/$studioId/shifts'
      preLoaderRoute: typeof StudiosStudioIdShiftsRouteImport
      parentRoute: typeof StudiosStudioIdRouteRoute
    }
    '/studios/$studioId/shared-fields': {
      id: '/studios/$studioId/shared-fields'
      path: '/shared-fields'
      fullPath: '/studios/$studioId/shared-fields'
      preLoaderRoute: typeof StudiosStudioIdSharedFieldsRouteImport
      parentRoute: typeof StudiosStudioIdRouteRoute
    }
    '/studios/$studioId/performance': {
      id: '/studios/$studioId/performance'
      path: '/performance'
      fullPath: '/studios/$studioId/performance'
      preLoaderRoute: typeof StudiosStudioIdPerformanceRouteImport
      parentRoute: typeof StudiosStudioIdRouteRoute
    }
    '/studios/$studioId/my-tasks': {
      id: '/studios/$studioId/my-tasks'
      path: '/my-tasks'
      fullPath: '/studios/$studioId/my-tasks'
      preLoaderRoute: typeof StudiosStudioIdMyTasksRouteImport
      parentRoute: typeof StudiosStudioIdRouteRoute
    }
    '/studios/$studioId/my-shifts': {
      id: '/studios/$studioId/my-shifts'
      path: '/my-shifts'
      fullPath: '/studios/$studioId/my-shifts'
      preLoaderRoute: typeof StudiosStudioIdMyShiftsRouteImport
      parentRoute: typeof StudiosStudioIdRouteRoute
    }
    '/studios/$studioId/my-compensations': {
      id: '/studios/$studioId/my-compensations'
      path: '/my-compensations'
      fullPath: '/studios/$studioId/my-compensations'
      preLoaderRoute: typeof StudiosStudioIdMyCompensationsRouteImport
      parentRoute: typeof StudiosStudioIdRouteRoute
    }
    '/studios/$studioId/members': {
      id: '/studios/$studioId/members'
      path: '/members'
      fullPath: '/studios/$studioId/members'
      preLoaderRoute: typeof StudiosStudioIdMembersRouteImport
      parentRoute: typeof StudiosStudioIdRouteRoute
    }
    '/studios/$studioId/dashboard': {
      id: '/studios/$studioId/dashboard'
      path: '/dashboard'
      fullPath: '/studios/$studioId/dashboard'
      preLoaderRoute: typeof StudiosStudioIdDashboardRouteImport
      parentRoute: typeof StudiosStudioIdRouteRoute
    }
    '/studios/$studioId/creators': {
      id: '/studios/$studioId/creators'
      path: '/creators'
      fullPath: '/studios/$studioId/creators'
      preLoaderRoute: typeof StudiosStudioIdCreatorsRouteImport
      parentRoute: typeof StudiosStudioIdRouteRoute
    }
    '/studios/$studioId/creator-mapping': {
      id: '/studios/$studioId/creator-mapping'
      path: '/creator-mapping'
      fullPath: '/studios/$studioId/creator-mapping'
      preLoaderRoute: typeof StudiosStudioIdCreatorMappingRouteImport
      parentRoute: typeof StudiosStudioIdRouteRoute
    }
    '/studios/$studioId/costs': {
      id: '/studios/$studioId/costs'
      path: '/costs'
      fullPath: '/studios/$studioId/costs'
      preLoaderRoute: typeof StudiosStudioIdCostsRouteImport
      parentRoute: typeof StudiosStudioIdRouteRoute
    }
    '/studios/$studioId/task-templates/': {
      id: '/studios/$studioId/task-templates/'
      path: '/'
      fullPath: '/studios/$studioId/task-templates/'
      preLoaderRoute: typeof StudiosStudioIdTaskTemplatesIndexRouteImport
      parentRoute: typeof StudiosStudioIdTaskTemplatesRoute
    }
    '/studios/$studioId/task-setup/': {
      id: '/studios/$studioId/task-setup/'
      path: '/'
      fullPath: '/studios/$studioId/task-setup/'
      preLoaderRoute: typeof StudiosStudioIdTaskSetupIndexRouteImport
      parentRoute: typeof StudiosStudioIdTaskSetupRoute
    }
    '/studios/$studioId/task-review/': {
      id: '/studios/$studioId/task-review/'
      path: '/'
      fullPath: '/studios/$studioId/task-review/'
      preLoaderRoute: typeof StudiosStudioIdTaskReviewIndexRouteImport
      parentRoute: typeof StudiosStudioIdTaskReviewRoute
    }
    '/studios/$studioId/task-reports/': {
      id: '/studios/$studioId/task-reports/'
      path: '/'
      fullPath: '/studios/$studioId/task-reports/'
      preLoaderRoute: typeof StudiosStudioIdTaskReportsIndexRouteImport
      parentRoute: typeof StudiosStudioIdTaskReportsRoute
    }
    '/studios/$studioId/shows/': {
      id: '/studios/$studioId/shows/'
      path: '/'
      fullPath: '/studios/$studioId/shows/'
      preLoaderRoute: typeof StudiosStudioIdShowsIndexRouteImport
      parentRoute: typeof StudiosStudioIdShowsRoute
    }
    '/studios/$studioId/shifts/': {
      id: '/studios/$studioId/shifts/'
      path: '/'
      fullPath: '/studios/$studioId/shifts/'
      preLoaderRoute: typeof StudiosStudioIdShiftsIndexRouteImport
      parentRoute: typeof StudiosStudioIdShiftsRoute
    }
    '/studios/$studioId/members/': {
      id: '/studios/$studioId/members/'
      path: '/'
      fullPath: '/studios/$studioId/members/'
      preLoaderRoute: typeof StudiosStudioIdMembersIndexRouteImport
      parentRoute: typeof StudiosStudioIdMembersRoute
    }
    '/studios/$studioId/creators/': {
      id: '/studios/$studioId/creators/'
      path: '/'
      fullPath: '/studios/$studioId/creators/'
      preLoaderRoute: typeof StudiosStudioIdCreatorsIndexRouteImport
      parentRoute: typeof StudiosStudioIdCreatorsRoute
    }
    '/studios/$studioId/creator-mapping/': {
      id: '/studios/$studioId/creator-mapping/'
      path: '/'
      fullPath: '/studios/$studioId/creator-mapping/'
      preLoaderRoute: typeof StudiosStudioIdCreatorMappingIndexRouteImport
      parentRoute: typeof StudiosStudioIdCreatorMappingRoute
    }
    '/system/shows/$showId/tasks': {
      id: '/system/shows/$showId/tasks'
      path: '/shows/$showId/tasks'
      fullPath: '/system/shows/$showId/tasks'
      preLoaderRoute: typeof SystemShowsShowIdTasksRouteImport
      parentRoute: typeof SystemRouteRoute
    }
    '/studios/$studioId/task-templates/new': {
      id: '/studios/$studioId/task-templates/new'
      path: '/new'
      fullPath: '/studios/$studioId/task-templates/new'
      preLoaderRoute: typeof StudiosStudioIdTaskTemplatesNewRouteImport
      parentRoute: typeof StudiosStudioIdTaskTemplatesRoute
    }
    '/studios/$studioId/task-templates/$templateId': {
      id: '/studios/$studioId/task-templates/$templateId'
      path: '/$templateId'
      fullPath: '/studios/$studioId/task-templates/$templateId'
      preLoaderRoute: typeof StudiosStudioIdTaskTemplatesTemplateIdRouteImport
      parentRoute: typeof StudiosStudioIdTaskTemplatesRoute
    }
    '/studios/$studioId/task-reports/results': {
      id: '/studios/$studioId/task-reports/results'
      path: '/results'
      fullPath: '/studios/$studioId/task-reports/results'
      preLoaderRoute: typeof StudiosStudioIdTaskReportsResultsRouteImport
      parentRoute: typeof StudiosStudioIdTaskReportsRoute
    }
    '/studios/$studioId/task-reports/builder': {
      id: '/studios/$studioId/task-reports/builder'
      path: '/builder'
      fullPath: '/studios/$studioId/task-reports/builder'
      preLoaderRoute: typeof StudiosStudioIdTaskReportsBuilderRouteImport
      parentRoute: typeof StudiosStudioIdTaskReportsRoute
    }
    '/studios/$studioId/shows/$showId': {
      id: '/studios/$studioId/shows/$showId'
      path: '/$showId'
      fullPath: '/studios/$studioId/shows/$showId'
      preLoaderRoute: typeof StudiosStudioIdShowsShowIdRouteRouteImport
      parentRoute: typeof StudiosStudioIdShowsRoute
    }
    '/studios/$studioId/shifts/$shiftId': {
      id: '/studios/$studioId/shifts/$shiftId'
      path: '/$shiftId'
      fullPath: '/studios/$studioId/shifts/$shiftId'
      preLoaderRoute: typeof StudiosStudioIdShiftsShiftIdRouteRouteImport
      parentRoute: typeof StudiosStudioIdShiftsRoute
    }
    '/studios/$studioId/members/$memberId': {
      id: '/studios/$studioId/members/$memberId'
      path: '/$memberId'
      fullPath: '/studios/$studioId/members/$memberId'
      preLoaderRoute: typeof StudiosStudioIdMembersMemberIdRouteRouteImport
      parentRoute: typeof StudiosStudioIdMembersRoute
    }
    '/studios/$studioId/creators/$creatorId': {
      id: '/studios/$studioId/creators/$creatorId'
      path: '/$creatorId'
      fullPath: '/studios/$studioId/creators/$creatorId'
      preLoaderRoute: typeof StudiosStudioIdCreatorsCreatorIdRouteRouteImport
      parentRoute: typeof StudiosStudioIdCreatorsRoute
    }
    '/system/studios/$studioId/studio-rooms/': {
      id: '/system/studios/$studioId/studio-rooms/'
      path: '/studios/$studioId/studio-rooms'
      fullPath: '/system/studios/$studioId/studio-rooms'
      preLoaderRoute: typeof SystemStudiosStudioIdStudioRoomsIndexRouteImport
      parentRoute: typeof SystemRouteRoute
    }
    '/system/schedules/$scheduleId/snapshots/': {
      id: '/system/schedules/$scheduleId/snapshots/'
      path: '/schedules/$scheduleId/snapshots'
      fullPath: '/system/schedules/$scheduleId/snapshots'
      preLoaderRoute: typeof SystemSchedulesScheduleIdSnapshotsIndexRouteImport
      parentRoute: typeof SystemRouteRoute
    }
    '/studios/$studioId/shows/$showId/': {
      id: '/studios/$studioId/shows/$showId/'
      path: '/'
      fullPath: '/studios/$studioId/shows/$showId/'
      preLoaderRoute: typeof StudiosStudioIdShowsShowIdIndexRouteImport
      parentRoute: typeof StudiosStudioIdShowsShowIdRouteRoute
    }
    '/studios/$studioId/shifts/$shiftId/': {
      id: '/studios/$studioId/shifts/$shiftId/'
      path: '/'
      fullPath: '/studios/$studioId/shifts/$shiftId/'
      preLoaderRoute: typeof StudiosStudioIdShiftsShiftIdIndexRouteImport
      parentRoute: typeof StudiosStudioIdShiftsShiftIdRouteRoute
    }
    '/studios/$studioId/members/$memberId/': {
      id: '/studios/$studioId/members/$memberId/'
      path: '/'
      fullPath: '/studios/$studioId/members/$memberId/'
      preLoaderRoute: typeof StudiosStudioIdMembersMemberIdIndexRouteImport
      parentRoute: typeof StudiosStudioIdMembersMemberIdRouteRoute
    }
    '/studios/$studioId/creators/$creatorId/': {
      id: '/studios/$studioId/creators/$creatorId/'
      path: '/'
      fullPath: '/studios/$studioId/creators/$creatorId/'
      preLoaderRoute: typeof StudiosStudioIdCreatorsCreatorIdIndexRouteImport
      parentRoute: typeof StudiosStudioIdCreatorsCreatorIdRouteRoute
    }
    '/studios/$studioId/shows/$showId/tasks': {
      id: '/studios/$studioId/shows/$showId/tasks'
      path: '/tasks'
      fullPath: '/studios/$studioId/shows/$showId/tasks'
      preLoaderRoute: typeof StudiosStudioIdShowsShowIdTasksRouteImport
      parentRoute: typeof StudiosStudioIdShowsShowIdRouteRoute
    }
    '/studios/$studioId/shows/$showId/performance': {
      id: '/studios/$studioId/shows/$showId/performance'
      path: '/performance'
      fullPath: '/studios/$studioId/shows/$showId/performance'
      preLoaderRoute: typeof StudiosStudioIdShowsShowIdPerformanceRouteImport
      parentRoute: typeof StudiosStudioIdShowsShowIdRouteRoute
    }
    '/studios/$studioId/shows/$showId/compensation': {
      id: '/studios/$studioId/shows/$showId/compensation'
      path: '/compensation'
      fullPath: '/studios/$studioId/shows/$showId/compensation'
      preLoaderRoute: typeof StudiosStudioIdShowsShowIdCompensationRouteImport
      parentRoute: typeof StudiosStudioIdShowsShowIdRouteRoute
    }
    '/studios/$studioId/shows/$showId/actuals': {
      id: '/studios/$studioId/shows/$showId/actuals'
      path: '/actuals'
      fullPath: '/studios/$studioId/shows/$showId/actuals'
      preLoaderRoute: typeof StudiosStudioIdShowsShowIdActualsRouteImport
      parentRoute: typeof StudiosStudioIdShowsShowIdRouteRoute
    }
    '/studios/$studioId/shifts/$shiftId/compensation': {
      id: '/studios/$studioId/shifts/$shiftId/compensation'
      path: '/compensation'
      fullPath: '/studios/$studioId/shifts/$shiftId/compensation'
      preLoaderRoute: typeof StudiosStudioIdShiftsShiftIdCompensationRouteImport
      parentRoute: typeof StudiosStudioIdShiftsShiftIdRouteRoute
    }
    '/studios/$studioId/members/$memberId/compensations': {
      id: '/studios/$studioId/members/$memberId/compensations'
      path: '/compensations'
      fullPath: '/studios/$studioId/members/$memberId/compensations'
      preLoaderRoute: typeof StudiosStudioIdMembersMemberIdCompensationsRouteImport
      parentRoute: typeof StudiosStudioIdMembersMemberIdRouteRoute
    }
    '/studios/$studioId/creators/$creatorId/compensations': {
      id: '/studios/$studioId/creators/$creatorId/compensations'
      path: '/compensations'
      fullPath: '/studios/$studioId/creators/$creatorId/compensations'
      preLoaderRoute: typeof StudiosStudioIdCreatorsCreatorIdCompensationsRouteImport
      parentRoute: typeof StudiosStudioIdCreatorsCreatorIdRouteRoute
    }
  }
}

interface StudiosStudioIdCreatorMappingRouteChildren {
  StudiosStudioIdCreatorMappingIndexRoute: typeof StudiosStudioIdCreatorMappingIndexRoute
}

const StudiosStudioIdCreatorMappingRouteChildren: StudiosStudioIdCreatorMappingRouteChildren =
  {
    StudiosStudioIdCreatorMappingIndexRoute:
      StudiosStudioIdCreatorMappingIndexRoute,
  }

const StudiosStudioIdCreatorMappingRouteWithChildren =
  StudiosStudioIdCreatorMappingRoute._addFileChildren(
    StudiosStudioIdCreatorMappingRouteChildren,
  )

interface StudiosStudioIdCreatorsCreatorIdRouteRouteChildren {
  StudiosStudioIdCreatorsCreatorIdCompensationsRoute: typeof StudiosStudioIdCreatorsCreatorIdCompensationsRoute
  StudiosStudioIdCreatorsCreatorIdIndexRoute: typeof StudiosStudioIdCreatorsCreatorIdIndexRoute
}

const StudiosStudioIdCreatorsCreatorIdRouteRouteChildren: StudiosStudioIdCreatorsCreatorIdRouteRouteChildren =
  {
    StudiosStudioIdCreatorsCreatorIdCompensationsRoute:
      StudiosStudioIdCreatorsCreatorIdCompensationsRoute,
    StudiosStudioIdCreatorsCreatorIdIndexRoute:
      StudiosStudioIdCreatorsCreatorIdIndexRoute,
  }

const StudiosStudioIdCreatorsCreatorIdRouteRouteWithChildren =
  StudiosStudioIdCreatorsCreatorIdRouteRoute._addFileChildren(
    StudiosStudioIdCreatorsCreatorIdRouteRouteChildren,
  )

interface StudiosStudioIdCreatorsRouteChildren {
  StudiosStudioIdCreatorsCreatorIdRouteRoute: typeof StudiosStudioIdCreatorsCreatorIdRouteRouteWithChildren
  StudiosStudioIdCreatorsIndexRoute: typeof StudiosStudioIdCreatorsIndexRoute
}

const StudiosStudioIdCreatorsRouteChildren: StudiosStudioIdCreatorsRouteChildren =
  {
    StudiosStudioIdCreatorsCreatorIdRouteRoute:
      StudiosStudioIdCreatorsCreatorIdRouteRouteWithChildren,
    StudiosStudioIdCreatorsIndexRoute: StudiosStudioIdCreatorsIndexRoute,
  }

const StudiosStudioIdCreatorsRouteWithChildren =
  StudiosStudioIdCreatorsRoute._addFileChildren(
    StudiosStudioIdCreatorsRouteChildren,
  )

interface StudiosStudioIdMembersMemberIdRouteRouteChildren {
  StudiosStudioIdMembersMemberIdCompensationsRoute: typeof StudiosStudioIdMembersMemberIdCompensationsRoute
  StudiosStudioIdMembersMemberIdIndexRoute: typeof StudiosStudioIdMembersMemberIdIndexRoute
}

const StudiosStudioIdMembersMemberIdRouteRouteChildren: StudiosStudioIdMembersMemberIdRouteRouteChildren =
  {
    StudiosStudioIdMembersMemberIdCompensationsRoute:
      StudiosStudioIdMembersMemberIdCompensationsRoute,
    StudiosStudioIdMembersMemberIdIndexRoute:
      StudiosStudioIdMembersMemberIdIndexRoute,
  }

const StudiosStudioIdMembersMemberIdRouteRouteWithChildren =
  StudiosStudioIdMembersMemberIdRouteRoute._addFileChildren(
    StudiosStudioIdMembersMemberIdRouteRouteChildren,
  )

interface StudiosStudioIdMembersRouteChildren {
  StudiosStudioIdMembersMemberIdRouteRoute: typeof StudiosStudioIdMembersMemberIdRouteRouteWithChildren
  StudiosStudioIdMembersIndexRoute: typeof StudiosStudioIdMembersIndexRoute
}

const StudiosStudioIdMembersRouteChildren: StudiosStudioIdMembersRouteChildren =
  {
    StudiosStudioIdMembersMemberIdRouteRoute:
      StudiosStudioIdMembersMemberIdRouteRouteWithChildren,
    StudiosStudioIdMembersIndexRoute: StudiosStudioIdMembersIndexRoute,
  }

const StudiosStudioIdMembersRouteWithChildren =
  StudiosStudioIdMembersRoute._addFileChildren(
    StudiosStudioIdMembersRouteChildren,
  )

interface StudiosStudioIdShiftsShiftIdRouteRouteChildren {
  StudiosStudioIdShiftsShiftIdCompensationRoute: typeof StudiosStudioIdShiftsShiftIdCompensationRoute
  StudiosStudioIdShiftsShiftIdIndexRoute: typeof StudiosStudioIdShiftsShiftIdIndexRoute
}

const StudiosStudioIdShiftsShiftIdRouteRouteChildren: StudiosStudioIdShiftsShiftIdRouteRouteChildren =
  {
    StudiosStudioIdShiftsShiftIdCompensationRoute:
      StudiosStudioIdShiftsShiftIdCompensationRoute,
    StudiosStudioIdShiftsShiftIdIndexRoute:
      StudiosStudioIdShiftsShiftIdIndexRoute,
  }

const StudiosStudioIdShiftsShiftIdRouteRouteWithChildren =
  StudiosStudioIdShiftsShiftIdRouteRoute._addFileChildren(
    StudiosStudioIdShiftsShiftIdRouteRouteChildren,
  )

interface StudiosStudioIdShiftsRouteChildren {
  StudiosStudioIdShiftsShiftIdRouteRoute: typeof StudiosStudioIdShiftsShiftIdRouteRouteWithChildren
  StudiosStudioIdShiftsIndexRoute: typeof StudiosStudioIdShiftsIndexRoute
}

const StudiosStudioIdShiftsRouteChildren: StudiosStudioIdShiftsRouteChildren = {
  StudiosStudioIdShiftsShiftIdRouteRoute:
    StudiosStudioIdShiftsShiftIdRouteRouteWithChildren,
  StudiosStudioIdShiftsIndexRoute: StudiosStudioIdShiftsIndexRoute,
}

const StudiosStudioIdShiftsRouteWithChildren =
  StudiosStudioIdShiftsRoute._addFileChildren(
    StudiosStudioIdShiftsRouteChildren,
  )

interface StudiosStudioIdShowsShowIdRouteRouteChildren {
  StudiosStudioIdShowsShowIdActualsRoute: typeof StudiosStudioIdShowsShowIdActualsRoute
  StudiosStudioIdShowsShowIdCompensationRoute: typeof StudiosStudioIdShowsShowIdCompensationRoute
  StudiosStudioIdShowsShowIdPerformanceRoute: typeof StudiosStudioIdShowsShowIdPerformanceRoute
  StudiosStudioIdShowsShowIdTasksRoute: typeof StudiosStudioIdShowsShowIdTasksRoute
  StudiosStudioIdShowsShowIdIndexRoute: typeof StudiosStudioIdShowsShowIdIndexRoute
}

const StudiosStudioIdShowsShowIdRouteRouteChildren: StudiosStudioIdShowsShowIdRouteRouteChildren =
  {
    StudiosStudioIdShowsShowIdActualsRoute:
      StudiosStudioIdShowsShowIdActualsRoute,
    StudiosStudioIdShowsShowIdCompensationRoute:
      StudiosStudioIdShowsShowIdCompensationRoute,
    StudiosStudioIdShowsShowIdPerformanceRoute:
      StudiosStudioIdShowsShowIdPerformanceRoute,
    StudiosStudioIdShowsShowIdTasksRoute: StudiosStudioIdShowsShowIdTasksRoute,
    StudiosStudioIdShowsShowIdIndexRoute: StudiosStudioIdShowsShowIdIndexRoute,
  }

const StudiosStudioIdShowsShowIdRouteRouteWithChildren =
  StudiosStudioIdShowsShowIdRouteRoute._addFileChildren(
    StudiosStudioIdShowsShowIdRouteRouteChildren,
  )

interface StudiosStudioIdShowsRouteChildren {
  StudiosStudioIdShowsShowIdRouteRoute: typeof StudiosStudioIdShowsShowIdRouteRouteWithChildren
  StudiosStudioIdShowsIndexRoute: typeof StudiosStudioIdShowsIndexRoute
}

const StudiosStudioIdShowsRouteChildren: StudiosStudioIdShowsRouteChildren = {
  StudiosStudioIdShowsShowIdRouteRoute:
    StudiosStudioIdShowsShowIdRouteRouteWithChildren,
  StudiosStudioIdShowsIndexRoute: StudiosStudioIdShowsIndexRoute,
}

const StudiosStudioIdShowsRouteWithChildren =
  StudiosStudioIdShowsRoute._addFileChildren(StudiosStudioIdShowsRouteChildren)

interface StudiosStudioIdTaskReportsRouteChildren {
  StudiosStudioIdTaskReportsBuilderRoute: typeof StudiosStudioIdTaskReportsBuilderRoute
  StudiosStudioIdTaskReportsResultsRoute: typeof StudiosStudioIdTaskReportsResultsRoute
  StudiosStudioIdTaskReportsIndexRoute: typeof StudiosStudioIdTaskReportsIndexRoute
}

const StudiosStudioIdTaskReportsRouteChildren: StudiosStudioIdTaskReportsRouteChildren =
  {
    StudiosStudioIdTaskReportsBuilderRoute:
      StudiosStudioIdTaskReportsBuilderRoute,
    StudiosStudioIdTaskReportsResultsRoute:
      StudiosStudioIdTaskReportsResultsRoute,
    StudiosStudioIdTaskReportsIndexRoute: StudiosStudioIdTaskReportsIndexRoute,
  }

const StudiosStudioIdTaskReportsRouteWithChildren =
  StudiosStudioIdTaskReportsRoute._addFileChildren(
    StudiosStudioIdTaskReportsRouteChildren,
  )

interface StudiosStudioIdTaskReviewRouteChildren {
  StudiosStudioIdTaskReviewIndexRoute: typeof StudiosStudioIdTaskReviewIndexRoute
}

const StudiosStudioIdTaskReviewRouteChildren: StudiosStudioIdTaskReviewRouteChildren =
  {
    StudiosStudioIdTaskReviewIndexRoute: StudiosStudioIdTaskReviewIndexRoute,
  }

const StudiosStudioIdTaskReviewRouteWithChildren =
  StudiosStudioIdTaskReviewRoute._addFileChildren(
    StudiosStudioIdTaskReviewRouteChildren,
  )

interface StudiosStudioIdTaskSetupRouteChildren {
  StudiosStudioIdTaskSetupIndexRoute: typeof StudiosStudioIdTaskSetupIndexRoute
}

const StudiosStudioIdTaskSetupRouteChildren: StudiosStudioIdTaskSetupRouteChildren =
  {
    StudiosStudioIdTaskSetupIndexRoute: StudiosStudioIdTaskSetupIndexRoute,
  }

const StudiosStudioIdTaskSetupRouteWithChildren =
  StudiosStudioIdTaskSetupRoute._addFileChildren(
    StudiosStudioIdTaskSetupRouteChildren,
  )

interface StudiosStudioIdTaskTemplatesRouteChildren {
  StudiosStudioIdTaskTemplatesTemplateIdRoute: typeof StudiosStudioIdTaskTemplatesTemplateIdRoute
  StudiosStudioIdTaskTemplatesNewRoute: typeof StudiosStudioIdTaskTemplatesNewRoute
  StudiosStudioIdTaskTemplatesIndexRoute: typeof StudiosStudioIdTaskTemplatesIndexRoute
}

const StudiosStudioIdTaskTemplatesRouteChildren: StudiosStudioIdTaskTemplatesRouteChildren =
  {
    StudiosStudioIdTaskTemplatesTemplateIdRoute:
      StudiosStudioIdTaskTemplatesTemplateIdRoute,
    StudiosStudioIdTaskTemplatesNewRoute: StudiosStudioIdTaskTemplatesNewRoute,
    StudiosStudioIdTaskTemplatesIndexRoute:
      StudiosStudioIdTaskTemplatesIndexRoute,
  }

const StudiosStudioIdTaskTemplatesRouteWithChildren =
  StudiosStudioIdTaskTemplatesRoute._addFileChildren(
    StudiosStudioIdTaskTemplatesRouteChildren,
  )

interface StudiosStudioIdRouteRouteChildren {
  StudiosStudioIdCostsRoute: typeof StudiosStudioIdCostsRoute
  StudiosStudioIdCreatorMappingRoute: typeof StudiosStudioIdCreatorMappingRouteWithChildren
  StudiosStudioIdCreatorsRoute: typeof StudiosStudioIdCreatorsRouteWithChildren
  StudiosStudioIdDashboardRoute: typeof StudiosStudioIdDashboardRoute
  StudiosStudioIdMembersRoute: typeof StudiosStudioIdMembersRouteWithChildren
  StudiosStudioIdMyCompensationsRoute: typeof StudiosStudioIdMyCompensationsRoute
  StudiosStudioIdMyShiftsRoute: typeof StudiosStudioIdMyShiftsRoute
  StudiosStudioIdMyTasksRoute: typeof StudiosStudioIdMyTasksRoute
  StudiosStudioIdPerformanceRoute: typeof StudiosStudioIdPerformanceRoute
  StudiosStudioIdSharedFieldsRoute: typeof StudiosStudioIdSharedFieldsRoute
  StudiosStudioIdShiftsRoute: typeof StudiosStudioIdShiftsRouteWithChildren
  StudiosStudioIdShowRunReviewRoute: typeof StudiosStudioIdShowRunReviewRoute
  StudiosStudioIdShowsRoute: typeof StudiosStudioIdShowsRouteWithChildren
  StudiosStudioIdTaskReportsRoute: typeof StudiosStudioIdTaskReportsRouteWithChildren
  StudiosStudioIdTaskReviewRoute: typeof StudiosStudioIdTaskReviewRouteWithChildren
  StudiosStudioIdTaskSetupRoute: typeof StudiosStudioIdTaskSetupRouteWithChildren
  StudiosStudioIdTaskTemplatesRoute: typeof StudiosStudioIdTaskTemplatesRouteWithChildren
}

const StudiosStudioIdRouteRouteChildren: StudiosStudioIdRouteRouteChildren = {
  StudiosStudioIdCostsRoute: StudiosStudioIdCostsRoute,
  StudiosStudioIdCreatorMappingRoute:
    StudiosStudioIdCreatorMappingRouteWithChildren,
  StudiosStudioIdCreatorsRoute: StudiosStudioIdCreatorsRouteWithChildren,
  StudiosStudioIdDashboardRoute: StudiosStudioIdDashboardRoute,
  StudiosStudioIdMembersRoute: StudiosStudioIdMembersRouteWithChildren,
  StudiosStudioIdMyCompensationsRoute: StudiosStudioIdMyCompensationsRoute,
  StudiosStudioIdMyShiftsRoute: StudiosStudioIdMyShiftsRoute,
  StudiosStudioIdMyTasksRoute: StudiosStudioIdMyTasksRoute,
  StudiosStudioIdPerformanceRoute: StudiosStudioIdPerformanceRoute,
  StudiosStudioIdSharedFieldsRoute: StudiosStudioIdSharedFieldsRoute,
  StudiosStudioIdShiftsRoute: StudiosStudioIdShiftsRouteWithChildren,
  StudiosStudioIdShowRunReviewRoute: StudiosStudioIdShowRunReviewRoute,
  StudiosStudioIdShowsRoute: StudiosStudioIdShowsRouteWithChildren,
  StudiosStudioIdTaskReportsRoute: StudiosStudioIdTaskReportsRouteWithChildren,
  StudiosStudioIdTaskReviewRoute: StudiosStudioIdTaskReviewRouteWithChildren,
  StudiosStudioIdTaskSetupRoute: StudiosStudioIdTaskSetupRouteWithChildren,
  StudiosStudioIdTaskTemplatesRoute:
    StudiosStudioIdTaskTemplatesRouteWithChildren,
}

const StudiosStudioIdRouteRouteWithChildren =
  StudiosStudioIdRouteRoute._addFileChildren(StudiosStudioIdRouteRouteChildren)

interface StudiosRouteRouteChildren {
  StudiosStudioIdRouteRoute: typeof StudiosStudioIdRouteRouteWithChildren
}

const StudiosRouteRouteChildren: StudiosRouteRouteChildren = {
  StudiosStudioIdRouteRoute: StudiosStudioIdRouteRouteWithChildren,
}

const StudiosRouteRouteWithChildren = StudiosRouteRoute._addFileChildren(
  StudiosRouteRouteChildren,
)

interface SystemRouteRouteChildren {
  SystemClientsIndexRoute: typeof SystemClientsIndexRoute
  SystemCompensationLineItemsIndexRoute: typeof SystemCompensationLineItemsIndexRoute
  SystemCreatorsIndexRoute: typeof SystemCreatorsIndexRoute
  SystemMembershipsIndexRoute: typeof SystemMembershipsIndexRoute
  SystemPlatformsIndexRoute: typeof SystemPlatformsIndexRoute
  SystemSchedulesIndexRoute: typeof SystemSchedulesIndexRoute
  SystemShowStandardsIndexRoute: typeof SystemShowStandardsIndexRoute
  SystemShowStatusesIndexRoute: typeof SystemShowStatusesIndexRoute
  SystemShowTypesIndexRoute: typeof SystemShowTypesIndexRoute
  SystemShowsIndexRoute: typeof SystemShowsIndexRoute
  SystemStudiosIndexRoute: typeof SystemStudiosIndexRoute
  SystemTaskTemplatesIndexRoute: typeof SystemTaskTemplatesIndexRoute
  SystemTasksIndexRoute: typeof SystemTasksIndexRoute
  SystemUsersIndexRoute: typeof SystemUsersIndexRoute
  SystemShowsShowIdTasksRoute: typeof SystemShowsShowIdTasksRoute
  SystemSchedulesScheduleIdSnapshotsIndexRoute: typeof SystemSchedulesScheduleIdSnapshotsIndexRoute
  SystemStudiosStudioIdStudioRoomsIndexRoute: typeof SystemStudiosStudioIdStudioRoomsIndexRoute
}

const SystemRouteRouteChildren: SystemRouteRouteChildren = {
  SystemClientsIndexRoute: SystemClientsIndexRoute,
  SystemCompensationLineItemsIndexRoute: SystemCompensationLineItemsIndexRoute,
  SystemCreatorsIndexRoute: SystemCreatorsIndexRoute,
  SystemMembershipsIndexRoute: SystemMembershipsIndexRoute,
  SystemPlatformsIndexRoute: SystemPlatformsIndexRoute,
  SystemSchedulesIndexRoute: SystemSchedulesIndexRoute,
  SystemShowStandardsIndexRoute: SystemShowStandardsIndexRoute,
  SystemShowStatusesIndexRoute: SystemShowStatusesIndexRoute,
  SystemShowTypesIndexRoute: SystemShowTypesIndexRoute,
  SystemShowsIndexRoute: SystemShowsIndexRoute,
  SystemStudiosIndexRoute: SystemStudiosIndexRoute,
  SystemTaskTemplatesIndexRoute: SystemTaskTemplatesIndexRoute,
  SystemTasksIndexRoute: SystemTasksIndexRoute,
  SystemUsersIndexRoute: SystemUsersIndexRoute,
  SystemShowsShowIdTasksRoute: SystemShowsShowIdTasksRoute,
  SystemSchedulesScheduleIdSnapshotsIndexRoute:
    SystemSchedulesScheduleIdSnapshotsIndexRoute,
  SystemStudiosStudioIdStudioRoomsIndexRoute:
    SystemStudiosStudioIdStudioRoomsIndexRoute,
}

const SystemRouteRouteWithChildren = SystemRouteRoute._addFileChildren(
  SystemRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StudiosRouteRoute: StudiosRouteRouteWithChildren,
  SystemRouteRoute: SystemRouteRouteWithChildren,
  DashboardRoute: DashboardRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
