/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as SystemRouteRouteImport } from './routes/system/route'
import { Route as StudiosRouteRouteImport } from './routes/studios/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SystemUsersIndexRouteImport } from './routes/system/users/index'
import { Route as SystemStudiosIndexRouteImport } from './routes/system/studios/index'
import { Route as SystemShowsIndexRouteImport } from './routes/system/shows/index'
import { Route as SystemShowTypesIndexRouteImport } from './routes/system/show-types/index'
import { Route as SystemShowStandardsIndexRouteImport } from './routes/system/show-standards/index'
import { Route as SystemSchedulesIndexRouteImport } from './routes/system/schedules/index'
import { Route as SystemPlatformsIndexRouteImport } from './routes/system/platforms/index'
import { Route as SystemMembershipsIndexRouteImport } from './routes/system/memberships/index'
import { Route as SystemMcsIndexRouteImport } from './routes/system/mcs/index'
import { Route as SystemClientsIndexRouteImport } from './routes/system/clients/index'
import { Route as StudiosStudioIdTaskTemplatesRouteImport } from './routes/studios/$studioId/task-templates'
import { Route as StudiosStudioIdMyTasksRouteImport } from './routes/studios/$studioId/my-tasks'
import { Route as StudiosStudioIdDashboardRouteImport } from './routes/studios/$studioId/dashboard'
import { Route as StudiosStudioIdTaskTemplatesIndexRouteImport } from './routes/studios/$studioId/task-templates/index'
import { Route as StudiosStudioIdTaskTemplatesNewRouteImport } from './routes/studios/$studioId/task-templates/new'
import { Route as StudiosStudioIdTaskTemplatesTemplateIdRouteImport } from './routes/studios/$studioId/task-templates/$templateId'
import { Route as SystemStudiosStudioIdStudioRoomsIndexRouteImport } from './routes/system/studios/$studioId/studio-rooms/index'
import { Route as SystemSchedulesScheduleIdSnapshotsIndexRouteImport } from './routes/system/schedules/$scheduleId/snapshots/index'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemRouteRoute = SystemRouteRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const StudiosRouteRoute = StudiosRouteRouteImport.update({
  id: '/studios',
  path: '/studios',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemUsersIndexRoute = SystemUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => SystemRouteRoute,
} as any)
const SystemStudiosIndexRoute = SystemStudiosIndexRouteImport.update({
  id: '/studios/',
  path: '/studios/',
  getParentRoute: () => SystemRouteRoute,
} as any)
const SystemShowsIndexRoute = SystemShowsIndexRouteImport.update({
  id: '/shows/',
  path: '/shows/',
  getParentRoute: () => SystemRouteRoute,
} as any)
const SystemShowTypesIndexRoute = SystemShowTypesIndexRouteImport.update({
  id: '/show-types/',
  path: '/show-types/',
  getParentRoute: () => SystemRouteRoute,
} as any)
const SystemShowStandardsIndexRoute =
  SystemShowStandardsIndexRouteImport.update({
    id: '/show-standards/',
    path: '/show-standards/',
    getParentRoute: () => SystemRouteRoute,
  } as any)
const SystemSchedulesIndexRoute = SystemSchedulesIndexRouteImport.update({
  id: '/schedules/',
  path: '/schedules/',
  getParentRoute: () => SystemRouteRoute,
} as any)
const SystemPlatformsIndexRoute = SystemPlatformsIndexRouteImport.update({
  id: '/platforms/',
  path: '/platforms/',
  getParentRoute: () => SystemRouteRoute,
} as any)
const SystemMembershipsIndexRoute = SystemMembershipsIndexRouteImport.update({
  id: '/memberships/',
  path: '/memberships/',
  getParentRoute: () => SystemRouteRoute,
} as any)
const SystemMcsIndexRoute = SystemMcsIndexRouteImport.update({
  id: '/mcs/',
  path: '/mcs/',
  getParentRoute: () => SystemRouteRoute,
} as any)
const SystemClientsIndexRoute = SystemClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => SystemRouteRoute,
} as any)
const StudiosStudioIdTaskTemplatesRoute =
  StudiosStudioIdTaskTemplatesRouteImport.update({
    id: '/$studioId/task-templates',
    path: '/$studioId/task-templates',
    getParentRoute: () => StudiosRouteRoute,
  } as any)
const StudiosStudioIdMyTasksRoute = StudiosStudioIdMyTasksRouteImport.update({
  id: '/$studioId/my-tasks',
  path: '/$studioId/my-tasks',
  getParentRoute: () => StudiosRouteRoute,
} as any)
const StudiosStudioIdDashboardRoute =
  StudiosStudioIdDashboardRouteImport.update({
    id: '/$studioId/dashboard',
    path: '/$studioId/dashboard',
    getParentRoute: () => StudiosRouteRoute,
  } as any)
const StudiosStudioIdTaskTemplatesIndexRoute =
  StudiosStudioIdTaskTemplatesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => StudiosStudioIdTaskTemplatesRoute,
  } as any)
const StudiosStudioIdTaskTemplatesNewRoute =
  StudiosStudioIdTaskTemplatesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => StudiosStudioIdTaskTemplatesRoute,
  } as any)
const StudiosStudioIdTaskTemplatesTemplateIdRoute =
  StudiosStudioIdTaskTemplatesTemplateIdRouteImport.update({
    id: '/$templateId',
    path: '/$templateId',
    getParentRoute: () => StudiosStudioIdTaskTemplatesRoute,
  } as any)
const SystemStudiosStudioIdStudioRoomsIndexRoute =
  SystemStudiosStudioIdStudioRoomsIndexRouteImport.update({
    id: '/studios/$studioId/studio-rooms/',
    path: '/studios/$studioId/studio-rooms/',
    getParentRoute: () => SystemRouteRoute,
  } as any)
const SystemSchedulesScheduleIdSnapshotsIndexRoute =
  SystemSchedulesScheduleIdSnapshotsIndexRouteImport.update({
    id: '/schedules/$scheduleId/snapshots/',
    path: '/schedules/$scheduleId/snapshots/',
    getParentRoute: () => SystemRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/studios': typeof StudiosRouteRouteWithChildren
  '/system': typeof SystemRouteRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/studios/$studioId/dashboard': typeof StudiosStudioIdDashboardRoute
  '/studios/$studioId/my-tasks': typeof StudiosStudioIdMyTasksRoute
  '/studios/$studioId/task-templates': typeof StudiosStudioIdTaskTemplatesRouteWithChildren
  '/system/clients': typeof SystemClientsIndexRoute
  '/system/mcs': typeof SystemMcsIndexRoute
  '/system/memberships': typeof SystemMembershipsIndexRoute
  '/system/platforms': typeof SystemPlatformsIndexRoute
  '/system/schedules': typeof SystemSchedulesIndexRoute
  '/system/show-standards': typeof SystemShowStandardsIndexRoute
  '/system/show-types': typeof SystemShowTypesIndexRoute
  '/system/shows': typeof SystemShowsIndexRoute
  '/system/studios': typeof SystemStudiosIndexRoute
  '/system/users': typeof SystemUsersIndexRoute
  '/studios/$studioId/task-templates/$templateId': typeof StudiosStudioIdTaskTemplatesTemplateIdRoute
  '/studios/$studioId/task-templates/new': typeof StudiosStudioIdTaskTemplatesNewRoute
  '/studios/$studioId/task-templates/': typeof StudiosStudioIdTaskTemplatesIndexRoute
  '/system/schedules/$scheduleId/snapshots': typeof SystemSchedulesScheduleIdSnapshotsIndexRoute
  '/system/studios/$studioId/studio-rooms': typeof SystemStudiosStudioIdStudioRoomsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/studios': typeof StudiosRouteRouteWithChildren
  '/system': typeof SystemRouteRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/studios/$studioId/dashboard': typeof StudiosStudioIdDashboardRoute
  '/studios/$studioId/my-tasks': typeof StudiosStudioIdMyTasksRoute
  '/system/clients': typeof SystemClientsIndexRoute
  '/system/mcs': typeof SystemMcsIndexRoute
  '/system/memberships': typeof SystemMembershipsIndexRoute
  '/system/platforms': typeof SystemPlatformsIndexRoute
  '/system/schedules': typeof SystemSchedulesIndexRoute
  '/system/show-standards': typeof SystemShowStandardsIndexRoute
  '/system/show-types': typeof SystemShowTypesIndexRoute
  '/system/shows': typeof SystemShowsIndexRoute
  '/system/studios': typeof SystemStudiosIndexRoute
  '/system/users': typeof SystemUsersIndexRoute
  '/studios/$studioId/task-templates/$templateId': typeof StudiosStudioIdTaskTemplatesTemplateIdRoute
  '/studios/$studioId/task-templates/new': typeof StudiosStudioIdTaskTemplatesNewRoute
  '/studios/$studioId/task-templates': typeof StudiosStudioIdTaskTemplatesIndexRoute
  '/system/schedules/$scheduleId/snapshots': typeof SystemSchedulesScheduleIdSnapshotsIndexRoute
  '/system/studios/$studioId/studio-rooms': typeof SystemStudiosStudioIdStudioRoomsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/studios': typeof StudiosRouteRouteWithChildren
  '/system': typeof SystemRouteRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/studios/$studioId/dashboard': typeof StudiosStudioIdDashboardRoute
  '/studios/$studioId/my-tasks': typeof StudiosStudioIdMyTasksRoute
  '/studios/$studioId/task-templates': typeof StudiosStudioIdTaskTemplatesRouteWithChildren
  '/system/clients/': typeof SystemClientsIndexRoute
  '/system/mcs/': typeof SystemMcsIndexRoute
  '/system/memberships/': typeof SystemMembershipsIndexRoute
  '/system/platforms/': typeof SystemPlatformsIndexRoute
  '/system/schedules/': typeof SystemSchedulesIndexRoute
  '/system/show-standards/': typeof SystemShowStandardsIndexRoute
  '/system/show-types/': typeof SystemShowTypesIndexRoute
  '/system/shows/': typeof SystemShowsIndexRoute
  '/system/studios/': typeof SystemStudiosIndexRoute
  '/system/users/': typeof SystemUsersIndexRoute
  '/studios/$studioId/task-templates/$templateId': typeof StudiosStudioIdTaskTemplatesTemplateIdRoute
  '/studios/$studioId/task-templates/new': typeof StudiosStudioIdTaskTemplatesNewRoute
  '/studios/$studioId/task-templates/': typeof StudiosStudioIdTaskTemplatesIndexRoute
  '/system/schedules/$scheduleId/snapshots/': typeof SystemSchedulesScheduleIdSnapshotsIndexRoute
  '/system/studios/$studioId/studio-rooms/': typeof SystemStudiosStudioIdStudioRoomsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/studios'
    | '/system'
    | '/dashboard'
    | '/studios/$studioId/dashboard'
    | '/studios/$studioId/my-tasks'
    | '/studios/$studioId/task-templates'
    | '/system/clients'
    | '/system/mcs'
    | '/system/memberships'
    | '/system/platforms'
    | '/system/schedules'
    | '/system/show-standards'
    | '/system/show-types'
    | '/system/shows'
    | '/system/studios'
    | '/system/users'
    | '/studios/$studioId/task-templates/$templateId'
    | '/studios/$studioId/task-templates/new'
    | '/studios/$studioId/task-templates/'
    | '/system/schedules/$scheduleId/snapshots'
    | '/system/studios/$studioId/studio-rooms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/studios'
    | '/system'
    | '/dashboard'
    | '/studios/$studioId/dashboard'
    | '/studios/$studioId/my-tasks'
    | '/system/clients'
    | '/system/mcs'
    | '/system/memberships'
    | '/system/platforms'
    | '/system/schedules'
    | '/system/show-standards'
    | '/system/show-types'
    | '/system/shows'
    | '/system/studios'
    | '/system/users'
    | '/studios/$studioId/task-templates/$templateId'
    | '/studios/$studioId/task-templates/new'
    | '/studios/$studioId/task-templates'
    | '/system/schedules/$scheduleId/snapshots'
    | '/system/studios/$studioId/studio-rooms'
  id:
    | '__root__'
    | '/'
    | '/studios'
    | '/system'
    | '/dashboard'
    | '/studios/$studioId/dashboard'
    | '/studios/$studioId/my-tasks'
    | '/studios/$studioId/task-templates'
    | '/system/clients/'
    | '/system/mcs/'
    | '/system/memberships/'
    | '/system/platforms/'
    | '/system/schedules/'
    | '/system/show-standards/'
    | '/system/show-types/'
    | '/system/shows/'
    | '/system/studios/'
    | '/system/users/'
    | '/studios/$studioId/task-templates/$templateId'
    | '/studios/$studioId/task-templates/new'
    | '/studios/$studioId/task-templates/'
    | '/system/schedules/$scheduleId/snapshots/'
    | '/system/studios/$studioId/studio-rooms/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StudiosRouteRoute: typeof StudiosRouteRouteWithChildren
  SystemRouteRoute: typeof SystemRouteRouteWithChildren
  DashboardRoute: typeof DashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studios': {
      id: '/studios'
      path: '/studios'
      fullPath: '/studios'
      preLoaderRoute: typeof StudiosRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/users/': {
      id: '/system/users/'
      path: '/users'
      fullPath: '/system/users'
      preLoaderRoute: typeof SystemUsersIndexRouteImport
      parentRoute: typeof SystemRouteRoute
    }
    '/system/studios/': {
      id: '/system/studios/'
      path: '/studios'
      fullPath: '/system/studios'
      preLoaderRoute: typeof SystemStudiosIndexRouteImport
      parentRoute: typeof SystemRouteRoute
    }
    '/system/shows/': {
      id: '/system/shows/'
      path: '/shows'
      fullPath: '/system/shows'
      preLoaderRoute: typeof SystemShowsIndexRouteImport
      parentRoute: typeof SystemRouteRoute
    }
    '/system/show-types/': {
      id: '/system/show-types/'
      path: '/show-types'
      fullPath: '/system/show-types'
      preLoaderRoute: typeof SystemShowTypesIndexRouteImport
      parentRoute: typeof SystemRouteRoute
    }
    '/system/show-standards/': {
      id: '/system/show-standards/'
      path: '/show-standards'
      fullPath: '/system/show-standards'
      preLoaderRoute: typeof SystemShowStandardsIndexRouteImport
      parentRoute: typeof SystemRouteRoute
    }
    '/system/schedules/': {
      id: '/system/schedules/'
      path: '/schedules'
      fullPath: '/system/schedules'
      preLoaderRoute: typeof SystemSchedulesIndexRouteImport
      parentRoute: typeof SystemRouteRoute
    }
    '/system/platforms/': {
      id: '/system/platforms/'
      path: '/platforms'
      fullPath: '/system/platforms'
      preLoaderRoute: typeof SystemPlatformsIndexRouteImport
      parentRoute: typeof SystemRouteRoute
    }
    '/system/memberships/': {
      id: '/system/memberships/'
      path: '/memberships'
      fullPath: '/system/memberships'
      preLoaderRoute: typeof SystemMembershipsIndexRouteImport
      parentRoute: typeof SystemRouteRoute
    }
    '/system/mcs/': {
      id: '/system/mcs/'
      path: '/mcs'
      fullPath: '/system/mcs'
      preLoaderRoute: typeof SystemMcsIndexRouteImport
      parentRoute: typeof SystemRouteRoute
    }
    '/system/clients/': {
      id: '/system/clients/'
      path: '/clients'
      fullPath: '/system/clients'
      preLoaderRoute: typeof SystemClientsIndexRouteImport
      parentRoute: typeof SystemRouteRoute
    }
    '/studios/$studioId/task-templates': {
      id: '/studios/$studioId/task-templates'
      path: '/$studioId/task-templates'
      fullPath: '/studios/$studioId/task-templates'
      preLoaderRoute: typeof StudiosStudioIdTaskTemplatesRouteImport
      parentRoute: typeof StudiosRouteRoute
    }
    '/studios/$studioId/my-tasks': {
      id: '/studios/$studioId/my-tasks'
      path: '/$studioId/my-tasks'
      fullPath: '/studios/$studioId/my-tasks'
      preLoaderRoute: typeof StudiosStudioIdMyTasksRouteImport
      parentRoute: typeof StudiosRouteRoute
    }
    '/studios/$studioId/dashboard': {
      id: '/studios/$studioId/dashboard'
      path: '/$studioId/dashboard'
      fullPath: '/studios/$studioId/dashboard'
      preLoaderRoute: typeof StudiosStudioIdDashboardRouteImport
      parentRoute: typeof StudiosRouteRoute
    }
    '/studios/$studioId/task-templates/': {
      id: '/studios/$studioId/task-templates/'
      path: '/'
      fullPath: '/studios/$studioId/task-templates/'
      preLoaderRoute: typeof StudiosStudioIdTaskTemplatesIndexRouteImport
      parentRoute: typeof StudiosStudioIdTaskTemplatesRoute
    }
    '/studios/$studioId/task-templates/new': {
      id: '/studios/$studioId/task-templates/new'
      path: '/new'
      fullPath: '/studios/$studioId/task-templates/new'
      preLoaderRoute: typeof StudiosStudioIdTaskTemplatesNewRouteImport
      parentRoute: typeof StudiosStudioIdTaskTemplatesRoute
    }
    '/studios/$studioId/task-templates/$templateId': {
      id: '/studios/$studioId/task-templates/$templateId'
      path: '/$templateId'
      fullPath: '/studios/$studioId/task-templates/$templateId'
      preLoaderRoute: typeof StudiosStudioIdTaskTemplatesTemplateIdRouteImport
      parentRoute: typeof StudiosStudioIdTaskTemplatesRoute
    }
    '/system/studios/$studioId/studio-rooms/': {
      id: '/system/studios/$studioId/studio-rooms/'
      path: '/studios/$studioId/studio-rooms'
      fullPath: '/system/studios/$studioId/studio-rooms'
      preLoaderRoute: typeof SystemStudiosStudioIdStudioRoomsIndexRouteImport
      parentRoute: typeof SystemRouteRoute
    }
    '/system/schedules/$scheduleId/snapshots/': {
      id: '/system/schedules/$scheduleId/snapshots/'
      path: '/schedules/$scheduleId/snapshots'
      fullPath: '/system/schedules/$scheduleId/snapshots'
      preLoaderRoute: typeof SystemSchedulesScheduleIdSnapshotsIndexRouteImport
      parentRoute: typeof SystemRouteRoute
    }
  }
}

interface StudiosStudioIdTaskTemplatesRouteChildren {
  StudiosStudioIdTaskTemplatesTemplateIdRoute: typeof StudiosStudioIdTaskTemplatesTemplateIdRoute
  StudiosStudioIdTaskTemplatesNewRoute: typeof StudiosStudioIdTaskTemplatesNewRoute
  StudiosStudioIdTaskTemplatesIndexRoute: typeof StudiosStudioIdTaskTemplatesIndexRoute
}

const StudiosStudioIdTaskTemplatesRouteChildren: StudiosStudioIdTaskTemplatesRouteChildren =
  {
    StudiosStudioIdTaskTemplatesTemplateIdRoute:
      StudiosStudioIdTaskTemplatesTemplateIdRoute,
    StudiosStudioIdTaskTemplatesNewRoute: StudiosStudioIdTaskTemplatesNewRoute,
    StudiosStudioIdTaskTemplatesIndexRoute:
      StudiosStudioIdTaskTemplatesIndexRoute,
  }

const StudiosStudioIdTaskTemplatesRouteWithChildren =
  StudiosStudioIdTaskTemplatesRoute._addFileChildren(
    StudiosStudioIdTaskTemplatesRouteChildren,
  )

interface StudiosRouteRouteChildren {
  StudiosStudioIdDashboardRoute: typeof StudiosStudioIdDashboardRoute
  StudiosStudioIdMyTasksRoute: typeof StudiosStudioIdMyTasksRoute
  StudiosStudioIdTaskTemplatesRoute: typeof StudiosStudioIdTaskTemplatesRouteWithChildren
}

const StudiosRouteRouteChildren: StudiosRouteRouteChildren = {
  StudiosStudioIdDashboardRoute: StudiosStudioIdDashboardRoute,
  StudiosStudioIdMyTasksRoute: StudiosStudioIdMyTasksRoute,
  StudiosStudioIdTaskTemplatesRoute:
    StudiosStudioIdTaskTemplatesRouteWithChildren,
}

const StudiosRouteRouteWithChildren = StudiosRouteRoute._addFileChildren(
  StudiosRouteRouteChildren,
)

interface SystemRouteRouteChildren {
  SystemClientsIndexRoute: typeof SystemClientsIndexRoute
  SystemMcsIndexRoute: typeof SystemMcsIndexRoute
  SystemMembershipsIndexRoute: typeof SystemMembershipsIndexRoute
  SystemPlatformsIndexRoute: typeof SystemPlatformsIndexRoute
  SystemSchedulesIndexRoute: typeof SystemSchedulesIndexRoute
  SystemShowStandardsIndexRoute: typeof SystemShowStandardsIndexRoute
  SystemShowTypesIndexRoute: typeof SystemShowTypesIndexRoute
  SystemShowsIndexRoute: typeof SystemShowsIndexRoute
  SystemStudiosIndexRoute: typeof SystemStudiosIndexRoute
  SystemUsersIndexRoute: typeof SystemUsersIndexRoute
  SystemSchedulesScheduleIdSnapshotsIndexRoute: typeof SystemSchedulesScheduleIdSnapshotsIndexRoute
  SystemStudiosStudioIdStudioRoomsIndexRoute: typeof SystemStudiosStudioIdStudioRoomsIndexRoute
}

const SystemRouteRouteChildren: SystemRouteRouteChildren = {
  SystemClientsIndexRoute: SystemClientsIndexRoute,
  SystemMcsIndexRoute: SystemMcsIndexRoute,
  SystemMembershipsIndexRoute: SystemMembershipsIndexRoute,
  SystemPlatformsIndexRoute: SystemPlatformsIndexRoute,
  SystemSchedulesIndexRoute: SystemSchedulesIndexRoute,
  SystemShowStandardsIndexRoute: SystemShowStandardsIndexRoute,
  SystemShowTypesIndexRoute: SystemShowTypesIndexRoute,
  SystemShowsIndexRoute: SystemShowsIndexRoute,
  SystemStudiosIndexRoute: SystemStudiosIndexRoute,
  SystemUsersIndexRoute: SystemUsersIndexRoute,
  SystemSchedulesScheduleIdSnapshotsIndexRoute:
    SystemSchedulesScheduleIdSnapshotsIndexRoute,
  SystemStudiosStudioIdStudioRoomsIndexRoute:
    SystemStudiosStudioIdStudioRoomsIndexRoute,
}

const SystemRouteRouteWithChildren = SystemRouteRoute._addFileChildren(
  SystemRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StudiosRouteRoute: StudiosRouteRouteWithChildren,
  SystemRouteRoute: SystemRouteRouteWithChildren,
  DashboardRoute: DashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
