/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as SystemRouteRouteImport } from './routes/system/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SystemUsersIndexRouteImport } from './routes/system/users/index'
import { Route as SystemStudiosIndexRouteImport } from './routes/system/studios/index'
import { Route as SystemShowTypesIndexRouteImport } from './routes/system/show-types/index'
import { Route as SystemShowStandardsIndexRouteImport } from './routes/system/show-standards/index'
import { Route as SystemPlatformsIndexRouteImport } from './routes/system/platforms/index'
import { Route as SystemMembershipsIndexRouteImport } from './routes/system/memberships/index'
import { Route as SystemMcsIndexRouteImport } from './routes/system/mcs/index'
import { Route as SystemClientsIndexRouteImport } from './routes/system/clients/index'
import { Route as AdminShowsIndexRouteImport } from './routes/admin/shows/index'
import { Route as AdminSchedulesIndexRouteImport } from './routes/admin/schedules/index'
import { Route as SystemStudiosStudioIdStudioRoomsIndexRouteImport } from './routes/system/studios/$studioId/studio-rooms/index'
import { Route as AdminSchedulesScheduleIdSnapshotsIndexRouteImport } from './routes/admin/schedules/$scheduleId/snapshots/index'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemRouteRoute = SystemRouteRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemUsersIndexRoute = SystemUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => SystemRouteRoute,
} as any)
const SystemStudiosIndexRoute = SystemStudiosIndexRouteImport.update({
  id: '/studios/',
  path: '/studios/',
  getParentRoute: () => SystemRouteRoute,
} as any)
const SystemShowTypesIndexRoute = SystemShowTypesIndexRouteImport.update({
  id: '/show-types/',
  path: '/show-types/',
  getParentRoute: () => SystemRouteRoute,
} as any)
const SystemShowStandardsIndexRoute =
  SystemShowStandardsIndexRouteImport.update({
    id: '/show-standards/',
    path: '/show-standards/',
    getParentRoute: () => SystemRouteRoute,
  } as any)
const SystemPlatformsIndexRoute = SystemPlatformsIndexRouteImport.update({
  id: '/platforms/',
  path: '/platforms/',
  getParentRoute: () => SystemRouteRoute,
} as any)
const SystemMembershipsIndexRoute = SystemMembershipsIndexRouteImport.update({
  id: '/memberships/',
  path: '/memberships/',
  getParentRoute: () => SystemRouteRoute,
} as any)
const SystemMcsIndexRoute = SystemMcsIndexRouteImport.update({
  id: '/mcs/',
  path: '/mcs/',
  getParentRoute: () => SystemRouteRoute,
} as any)
const SystemClientsIndexRoute = SystemClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => SystemRouteRoute,
} as any)
const AdminShowsIndexRoute = AdminShowsIndexRouteImport.update({
  id: '/shows/',
  path: '/shows/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSchedulesIndexRoute = AdminSchedulesIndexRouteImport.update({
  id: '/schedules/',
  path: '/schedules/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const SystemStudiosStudioIdStudioRoomsIndexRoute =
  SystemStudiosStudioIdStudioRoomsIndexRouteImport.update({
    id: '/studios/$studioId/studio-rooms/',
    path: '/studios/$studioId/studio-rooms/',
    getParentRoute: () => SystemRouteRoute,
  } as any)
const AdminSchedulesScheduleIdSnapshotsIndexRoute =
  AdminSchedulesScheduleIdSnapshotsIndexRouteImport.update({
    id: '/schedules/$scheduleId/snapshots/',
    path: '/schedules/$scheduleId/snapshots/',
    getParentRoute: () => AdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/system': typeof SystemRouteRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/admin/schedules': typeof AdminSchedulesIndexRoute
  '/admin/shows': typeof AdminShowsIndexRoute
  '/system/clients': typeof SystemClientsIndexRoute
  '/system/mcs': typeof SystemMcsIndexRoute
  '/system/memberships': typeof SystemMembershipsIndexRoute
  '/system/platforms': typeof SystemPlatformsIndexRoute
  '/system/show-standards': typeof SystemShowStandardsIndexRoute
  '/system/show-types': typeof SystemShowTypesIndexRoute
  '/system/studios': typeof SystemStudiosIndexRoute
  '/system/users': typeof SystemUsersIndexRoute
  '/admin/schedules/$scheduleId/snapshots': typeof AdminSchedulesScheduleIdSnapshotsIndexRoute
  '/system/studios/$studioId/studio-rooms': typeof SystemStudiosStudioIdStudioRoomsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/system': typeof SystemRouteRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/admin/schedules': typeof AdminSchedulesIndexRoute
  '/admin/shows': typeof AdminShowsIndexRoute
  '/system/clients': typeof SystemClientsIndexRoute
  '/system/mcs': typeof SystemMcsIndexRoute
  '/system/memberships': typeof SystemMembershipsIndexRoute
  '/system/platforms': typeof SystemPlatformsIndexRoute
  '/system/show-standards': typeof SystemShowStandardsIndexRoute
  '/system/show-types': typeof SystemShowTypesIndexRoute
  '/system/studios': typeof SystemStudiosIndexRoute
  '/system/users': typeof SystemUsersIndexRoute
  '/admin/schedules/$scheduleId/snapshots': typeof AdminSchedulesScheduleIdSnapshotsIndexRoute
  '/system/studios/$studioId/studio-rooms': typeof SystemStudiosStudioIdStudioRoomsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/system': typeof SystemRouteRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/admin/schedules/': typeof AdminSchedulesIndexRoute
  '/admin/shows/': typeof AdminShowsIndexRoute
  '/system/clients/': typeof SystemClientsIndexRoute
  '/system/mcs/': typeof SystemMcsIndexRoute
  '/system/memberships/': typeof SystemMembershipsIndexRoute
  '/system/platforms/': typeof SystemPlatformsIndexRoute
  '/system/show-standards/': typeof SystemShowStandardsIndexRoute
  '/system/show-types/': typeof SystemShowTypesIndexRoute
  '/system/studios/': typeof SystemStudiosIndexRoute
  '/system/users/': typeof SystemUsersIndexRoute
  '/admin/schedules/$scheduleId/snapshots/': typeof AdminSchedulesScheduleIdSnapshotsIndexRoute
  '/system/studios/$studioId/studio-rooms/': typeof SystemStudiosStudioIdStudioRoomsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/system'
    | '/dashboard'
    | '/admin/schedules'
    | '/admin/shows'
    | '/system/clients'
    | '/system/mcs'
    | '/system/memberships'
    | '/system/platforms'
    | '/system/show-standards'
    | '/system/show-types'
    | '/system/studios'
    | '/system/users'
    | '/admin/schedules/$scheduleId/snapshots'
    | '/system/studios/$studioId/studio-rooms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/system'
    | '/dashboard'
    | '/admin/schedules'
    | '/admin/shows'
    | '/system/clients'
    | '/system/mcs'
    | '/system/memberships'
    | '/system/platforms'
    | '/system/show-standards'
    | '/system/show-types'
    | '/system/studios'
    | '/system/users'
    | '/admin/schedules/$scheduleId/snapshots'
    | '/system/studios/$studioId/studio-rooms'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/system'
    | '/dashboard'
    | '/admin/schedules/'
    | '/admin/shows/'
    | '/system/clients/'
    | '/system/mcs/'
    | '/system/memberships/'
    | '/system/platforms/'
    | '/system/show-standards/'
    | '/system/show-types/'
    | '/system/studios/'
    | '/system/users/'
    | '/admin/schedules/$scheduleId/snapshots/'
    | '/system/studios/$studioId/studio-rooms/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  SystemRouteRoute: typeof SystemRouteRouteWithChildren
  DashboardRoute: typeof DashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/users/': {
      id: '/system/users/'
      path: '/users'
      fullPath: '/system/users'
      preLoaderRoute: typeof SystemUsersIndexRouteImport
      parentRoute: typeof SystemRouteRoute
    }
    '/system/studios/': {
      id: '/system/studios/'
      path: '/studios'
      fullPath: '/system/studios'
      preLoaderRoute: typeof SystemStudiosIndexRouteImport
      parentRoute: typeof SystemRouteRoute
    }
    '/system/show-types/': {
      id: '/system/show-types/'
      path: '/show-types'
      fullPath: '/system/show-types'
      preLoaderRoute: typeof SystemShowTypesIndexRouteImport
      parentRoute: typeof SystemRouteRoute
    }
    '/system/show-standards/': {
      id: '/system/show-standards/'
      path: '/show-standards'
      fullPath: '/system/show-standards'
      preLoaderRoute: typeof SystemShowStandardsIndexRouteImport
      parentRoute: typeof SystemRouteRoute
    }
    '/system/platforms/': {
      id: '/system/platforms/'
      path: '/platforms'
      fullPath: '/system/platforms'
      preLoaderRoute: typeof SystemPlatformsIndexRouteImport
      parentRoute: typeof SystemRouteRoute
    }
    '/system/memberships/': {
      id: '/system/memberships/'
      path: '/memberships'
      fullPath: '/system/memberships'
      preLoaderRoute: typeof SystemMembershipsIndexRouteImport
      parentRoute: typeof SystemRouteRoute
    }
    '/system/mcs/': {
      id: '/system/mcs/'
      path: '/mcs'
      fullPath: '/system/mcs'
      preLoaderRoute: typeof SystemMcsIndexRouteImport
      parentRoute: typeof SystemRouteRoute
    }
    '/system/clients/': {
      id: '/system/clients/'
      path: '/clients'
      fullPath: '/system/clients'
      preLoaderRoute: typeof SystemClientsIndexRouteImport
      parentRoute: typeof SystemRouteRoute
    }
    '/admin/shows/': {
      id: '/admin/shows/'
      path: '/shows'
      fullPath: '/admin/shows'
      preLoaderRoute: typeof AdminShowsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/schedules/': {
      id: '/admin/schedules/'
      path: '/schedules'
      fullPath: '/admin/schedules'
      preLoaderRoute: typeof AdminSchedulesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/system/studios/$studioId/studio-rooms/': {
      id: '/system/studios/$studioId/studio-rooms/'
      path: '/studios/$studioId/studio-rooms'
      fullPath: '/system/studios/$studioId/studio-rooms'
      preLoaderRoute: typeof SystemStudiosStudioIdStudioRoomsIndexRouteImport
      parentRoute: typeof SystemRouteRoute
    }
    '/admin/schedules/$scheduleId/snapshots/': {
      id: '/admin/schedules/$scheduleId/snapshots/'
      path: '/schedules/$scheduleId/snapshots'
      fullPath: '/admin/schedules/$scheduleId/snapshots'
      preLoaderRoute: typeof AdminSchedulesScheduleIdSnapshotsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminSchedulesIndexRoute: typeof AdminSchedulesIndexRoute
  AdminShowsIndexRoute: typeof AdminShowsIndexRoute
  AdminSchedulesScheduleIdSnapshotsIndexRoute: typeof AdminSchedulesScheduleIdSnapshotsIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminSchedulesIndexRoute: AdminSchedulesIndexRoute,
  AdminShowsIndexRoute: AdminShowsIndexRoute,
  AdminSchedulesScheduleIdSnapshotsIndexRoute:
    AdminSchedulesScheduleIdSnapshotsIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface SystemRouteRouteChildren {
  SystemClientsIndexRoute: typeof SystemClientsIndexRoute
  SystemMcsIndexRoute: typeof SystemMcsIndexRoute
  SystemMembershipsIndexRoute: typeof SystemMembershipsIndexRoute
  SystemPlatformsIndexRoute: typeof SystemPlatformsIndexRoute
  SystemShowStandardsIndexRoute: typeof SystemShowStandardsIndexRoute
  SystemShowTypesIndexRoute: typeof SystemShowTypesIndexRoute
  SystemStudiosIndexRoute: typeof SystemStudiosIndexRoute
  SystemUsersIndexRoute: typeof SystemUsersIndexRoute
  SystemStudiosStudioIdStudioRoomsIndexRoute: typeof SystemStudiosStudioIdStudioRoomsIndexRoute
}

const SystemRouteRouteChildren: SystemRouteRouteChildren = {
  SystemClientsIndexRoute: SystemClientsIndexRoute,
  SystemMcsIndexRoute: SystemMcsIndexRoute,
  SystemMembershipsIndexRoute: SystemMembershipsIndexRoute,
  SystemPlatformsIndexRoute: SystemPlatformsIndexRoute,
  SystemShowStandardsIndexRoute: SystemShowStandardsIndexRoute,
  SystemShowTypesIndexRoute: SystemShowTypesIndexRoute,
  SystemStudiosIndexRoute: SystemStudiosIndexRoute,
  SystemUsersIndexRoute: SystemUsersIndexRoute,
  SystemStudiosStudioIdStudioRoomsIndexRoute:
    SystemStudiosStudioIdStudioRoomsIndexRoute,
}

const SystemRouteRouteWithChildren = SystemRouteRoute._addFileChildren(
  SystemRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  SystemRouteRoute: SystemRouteRouteWithChildren,
  DashboardRoute: DashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
