export const STUDIO_MEMBER_MAP_DEFAULT_LIMIT = 200;
export const STUDIO_MEMBER_MAP_CALENDAR_LIMIT = 500;

export const DASHBOARD_DUTY_SHIFTS_LIMIT = 200;
export const DASHBOARD_MY_SHIFTS_QUERY_LIMIT = 20;
export const DASHBOARD_MY_UPCOMING_SHIFTS_LIMIT = 5;
