/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShowsIndexRouteImport } from './routes/shows/index'
import { Route as CompensationsIndexRouteImport } from './routes/compensations/index'
import { Route as ShowsShowIdRouteImport } from './routes/shows/$showId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowsIndexRoute = ShowsIndexRouteImport.update({
  id: '/shows/',
  path: '/shows/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompensationsIndexRoute = CompensationsIndexRouteImport.update({
  id: '/compensations/',
  path: '/compensations/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowsShowIdRoute = ShowsShowIdRouteImport.update({
  id: '/shows/$showId',
  path: '/shows/$showId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/settings': typeof SettingsRoute
  '/shows/$showId': typeof ShowsShowIdRoute
  '/compensations': typeof CompensationsIndexRoute
  '/shows': typeof ShowsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/settings': typeof SettingsRoute
  '/shows/$showId': typeof ShowsShowIdRoute
  '/compensations': typeof CompensationsIndexRoute
  '/shows': typeof ShowsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/settings': typeof SettingsRoute
  '/shows/$showId': typeof ShowsShowIdRoute
  '/compensations/': typeof CompensationsIndexRoute
  '/shows/': typeof ShowsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/settings'
    | '/shows/$showId'
    | '/compensations'
    | '/shows'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$' | '/settings' | '/shows/$showId' | '/compensations' | '/shows'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/settings'
    | '/shows/$showId'
    | '/compensations/'
    | '/shows/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  SettingsRoute: typeof SettingsRoute
  ShowsShowIdRoute: typeof ShowsShowIdRoute
  CompensationsIndexRoute: typeof CompensationsIndexRoute
  ShowsIndexRoute: typeof ShowsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shows/': {
      id: '/shows/'
      path: '/shows'
      fullPath: '/shows'
      preLoaderRoute: typeof ShowsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compensations/': {
      id: '/compensations/'
      path: '/compensations'
      fullPath: '/compensations'
      preLoaderRoute: typeof CompensationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shows/$showId': {
      id: '/shows/$showId'
      path: '/shows/$showId'
      fullPath: '/shows/$showId'
      preLoaderRoute: typeof ShowsShowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  SettingsRoute: SettingsRoute,
  ShowsShowIdRoute: ShowsShowIdRoute,
  CompensationsIndexRoute: CompensationsIndexRoute,
  ShowsIndexRoute: ShowsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
