#!/usr/bin/env sh
# Load nvm if available
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

# Run eslint
pnpm lint

# Run markdown format check
pnpm lint:markdown

# Run sherif to check dependency versions
pnpm sherif
